export interface CalculatorMeta {
  slug: string;
  name: string;
  shortName: string;
  category: 'financial' | 'fitness' | 'math' | 'lifestyle';
  description: string;
  keywords: string[];
  icon: string; // emoji
}

export const CALCULATORS: CalculatorMeta[] = [
  {
    slug: 'mortgage',
    name: 'Mortgage Calculator',
    shortName: 'Mortgage',
    category: 'financial',
    description:
      'Calculate your monthly mortgage payment including principal, interest, taxes, and insurance (PITI). See the full amortization schedule.',
    keywords: ['mortgage calculator', 'home loan calculator', 'piti calculator', 'house payment', 'monthly mortgage payment'],
    icon: '🏠',
  },
  {
    slug: 'mortgage-amortization',
    name: 'Mortgage Amortization Calculator',
    shortName: 'Amortization',
    category: 'financial',
    description:
      'View the complete amortization schedule for any mortgage. See exactly how each payment is split between principal and interest, year by year.',
    keywords: ['mortgage amortization calculator', 'amortization schedule', 'loan amortization', 'mortgage payoff', 'extra payment calculator'],
    icon: '📅',
  },
  {
    slug: 'house-affordability',
    name: 'House Affordability Calculator',
    shortName: 'Affordability',
    category: 'financial',
    description:
      'Find out how much house you can afford based on your income, debts, and down payment. Uses the 28/36 DTI rule used by mortgage lenders.',
    keywords: ['house affordability calculator', 'how much house can i afford', 'home affordability', 'mortgage affordability', 'dti calculator'],
    icon: '🏡',
  },
  {
    slug: 'rent',
    name: 'Rent Calculator',
    shortName: 'Rent',
    category: 'financial',
    description:
      'Calculate your true total cost of renting including utilities, insurance, parking, and fees. See 10-year projections with annual rent increases.',
    keywords: ['rent calculator', 'cost of renting', 'monthly rent calculator', 'rental cost calculator', 'rent affordability'],
    icon: '🏢',
  },
  {
    slug: 'rent-vs-buy',
    name: 'Rent vs. Buy Calculator',
    shortName: 'Rent vs. Buy',
    category: 'financial',
    description:
      'Compare the true financial cost of renting versus buying a home over time. Find your break-even year and net cost difference.',
    keywords: ['rent vs buy calculator', 'renting vs buying', 'rent or buy', 'buy vs rent', 'break even buying house'],
    icon: '⚖️',
  },
  {
    slug: 'age',
    name: 'Age Calculator',
    shortName: 'Age',
    category: 'lifestyle',
    description:
      'Calculate your exact age in years, months, days, hours, and minutes. Find out how many days until your next birthday.',
    keywords: ['age calculator', 'birthday calculator', 'how old am i', 'age in days'],
    icon: '🎂',
  },
  { slug: 'pace', name: 'Pace Calculator', shortName: 'Pace', category: 'fitness', description: 'Calculate running pace from distance and elapsed time.', keywords: ['pace calculator','running pace calculator'], icon: '🏃' },
  { slug: 'gfr', name: 'GFR Calculator', shortName: 'GFR', category: 'fitness', description: 'Estimate adult eGFR with the race-free CKD-EPI 2021 creatinine equation.', keywords: ['gfr calculator','egfr calculator','ckd epi 2021'], icon: '🧪' },
  { slug: 'bac', name: 'BAC Calculator', shortName: 'BAC', category: 'fitness', description: 'Estimate blood alcohol concentration using a Widmark-style model.', keywords: ['bac calculator','blood alcohol calculator'], icon: '⚠️' },
  { slug: 'scientific', name: 'Scientific Calculator', shortName: 'Scientific', category: 'math', description: 'Evaluate common scientific functions with safe client-side inputs.', keywords: ['scientific calculator','sin cos log calculator'], icon: '🧮' },
  { slug: 'fraction', name: 'Fraction Calculator', shortName: 'Fraction', category: 'math', description: 'Add and reduce two fractions.', keywords: ['fraction calculator','fraction addition'], icon: '½' },
  { slug: 'standard-deviation', name: 'Standard Deviation Calculator', shortName: 'Standard Deviation', category: 'math', description: 'Calculate population standard deviation and mean for four inputs.', keywords: ['standard deviation calculator','population standard deviation'], icon: 'σ' },
  { slug: 'ratio', name: 'Ratio Calculator', shortName: 'Ratio', category: 'math', description: 'Simplify a ratio and show its decimal form.', keywords: ['ratio calculator','simplify ratio'], icon: '∶' },
  { slug: 'quadratic-formula', name: 'Quadratic Formula Calculator', shortName: 'Quadratic Formula', category: 'math', description: 'Solve a quadratic equation and report its discriminant.', keywords: ['quadratic formula calculator','quadratic equation solver'], icon: 'x²' },
  { slug: 'exponent', name: 'Exponent Calculator', shortName: 'Exponent', category: 'math', description: 'Calculate a number raised to a power.', keywords: ['exponent calculator','power calculator'], icon: 'xʸ' },
  { slug: 'root', name: 'Root Calculator', shortName: 'Root', category: 'math', description: 'Calculate an nth root.', keywords: ['root calculator','nth root calculator'], icon: '√' },
  { slug: 'log', name: 'Log Calculator', shortName: 'Log', category: 'math', description: 'Calculate a logarithm for a positive value and valid base.', keywords: ['log calculator','logarithm calculator'], icon: '㏒' },
  { slug: 'percent-error', name: 'Percent Error Calculator', shortName: 'Percent Error', category: 'math', description: 'Calculate absolute percent error against a theoretical value.', keywords: ['percent error calculator','percentage error'], icon: '%' },
  { slug: 'rounding', name: 'Rounding Calculator', shortName: 'Rounding', category: 'math', description: 'Round a value to a selected number of decimal places.', keywords: ['rounding calculator','round decimals'], icon: '≈' },
  { slug: 'triangle', name: 'Triangle Calculator', shortName: 'Triangle', category: 'math', description: 'Calculate right-triangle area and hypotenuse.', keywords: ['triangle calculator'], icon: '∑' },
  { slug: 'volume', name: 'Volume Calculator', shortName: 'Volume', category: 'math', description: 'Calculate rectangular-prism volume.', keywords: ['volume calculator'], icon: '∑' },
  { slug: 'number-sequence', name: 'Number Sequence Calculator', shortName: 'Number Sequence', category: 'math', description: 'Generate an arithmetic sequence and sum.', keywords: ['number-sequence calculator'], icon: '∑' },
  { slug: 'binary', name: 'Binary Calculator', shortName: 'Binary', category: 'math', description: 'Convert a non-negative integer to binary.', keywords: ['binary calculator'], icon: '∑' },
  { slug: 'hex', name: 'Hex Calculator', shortName: 'Hex', category: 'math', description: 'Convert a non-negative integer to hexadecimal.', keywords: ['hex calculator'], icon: '∑' },
  { slug: 'half-life', name: 'Half-Life Calculator', shortName: 'Half-Life', category: 'math', description: 'Calculate remaining quantity after radioactive-style decay.', keywords: ['half-life calculator'], icon: '∑' },
  { slug: 'slope', name: 'Slope Calculator', shortName: 'Slope', category: 'math', description: 'Calculate slope and intercept from two points.', keywords: ['slope calculator'], icon: '∑' },
  { slug: 'area', name: 'Area Calculator', shortName: 'Area', category: 'math', description: 'Calculate area using explicit client-side inputs.', keywords: ['area calculator'], icon: '∑' },
  { slug: 'distance', name: 'Distance Calculator', shortName: 'Distance', category: 'math', description: 'Calculate distance using explicit client-side inputs.', keywords: ['distance calculator'], icon: '∑' },
  { slug: 'sample-size', name: 'Sample Size Calculator', shortName: 'Sample Size', category: 'math', description: 'Calculate sample size using explicit client-side inputs.', keywords: ['sample-size calculator'], icon: '∑' },
  { slug: 'probability', name: 'Probability Calculator', shortName: 'Probability', category: 'math', description: 'Calculate probability using explicit client-side inputs.', keywords: ['probability calculator'], icon: '∑' },
  { slug: 'statistics', name: 'Statistics Calculator', shortName: 'Statistics', category: 'math', description: 'Calculate statistics using explicit client-side inputs.', keywords: ['statistics calculator'], icon: '∑' },
  { slug: 'permutation-and-combination', name: 'Permutation and Combination Calculator', shortName: 'Permutation and Combination', category: 'math', description: 'Calculate permutation and combination using explicit client-side inputs.', keywords: ['permutation-and-combination calculator'], icon: '∑' },
  { slug: 'factorial', name: 'Factorial Calculator', shortName: 'Factorial', category: 'math', description: 'Calculate n factorial for a non-negative integer.', keywords: ['factorial calculator', 'n factorial'] , icon: '!' },
  { slug: 'combination', name: 'Combination Calculator', shortName: 'Combination', category: 'math', description: 'Calculate unordered combinations from n items selecting r.', keywords: ['combination calculator', 'n choose r'], icon: 'C' },
  { slug: 'percentile', name: 'Percentile Calculator', shortName: 'Percentile', category: 'math', description: 'Estimate the median percentile from four displayed observations.', keywords: ['percentile calculator', 'median calculator'], icon: '%' },
  { slug: 'circle', name: 'Circle Calculator', shortName: 'Circle', category: 'math', description: 'Calculate circle with guarded client-side formulas.', keywords: ['circle calculator'], icon: '△' },
  { slug: 'surface-area', name: 'Surface Area Calculator', shortName: 'Surface Area', category: 'math', description: 'Calculate surface area with guarded client-side formulas.', keywords: ['surface-area calculator'], icon: '△' },
  { slug: 'pythagorean-theorem', name: 'Pythagorean Theorem Calculator', shortName: 'Pythagorean Theorem', category: 'math', description: 'Calculate pythagorean theorem with guarded client-side formulas.', keywords: ['pythagorean-theorem calculator'], icon: '△' },
  { slug: 'right-triangle', name: 'Right Triangle Calculator', shortName: 'Right Triangle', category: 'math', description: 'Calculate right triangle with guarded client-side formulas.', keywords: ['right-triangle calculator'], icon: '△' },
  { slug: 'least-common-multiple', name: 'Least Common Multiple Calculator', shortName: 'Least Common Multiple', category: 'math', description: 'Calculate least common multiple with guarded client-side formulas.', keywords: ['least-common-multiple calculator'], icon: '△' },
  { slug: 'greatest-common-factor', name: 'Greatest Common Factor Calculator', shortName: 'Greatest Common Factor', category: 'math', description: 'Calculate greatest common factor with guarded client-side formulas.', keywords: ['greatest-common-factor calculator'], icon: '△' },
  { slug: 'prime-factorization', name: 'Prime Factorization Calculator', shortName: 'Prime Factorization', category: 'math', description: 'Calculate prime factorization with guarded client-side formulas.', keywords: ['prime-factorization calculator'], icon: '△' },
  { slug: 'z-score', name: 'Z-score Calculator', shortName: 'Z-score', category: 'math', description: 'Calculate z-score from explicit statistical inputs.', keywords: ['z-score calculator'], icon: 'σ' },
  { slug: 'confidence-interval', name: 'Confidence Interval Calculator', shortName: 'Confidence Interval', category: 'math', description: 'Calculate confidence interval from explicit statistical inputs.', keywords: ['confidence-interval calculator'], icon: 'σ' },
  { slug: 'mean-median-mode-range', name: 'Mean, Median, Mode, Range Calculator', shortName: 'Mean, Median, Mode, Range', category: 'math', description: 'Calculate mean, median, mode, range from explicit statistical inputs.', keywords: ['mean-median-mode-range calculator'], icon: 'σ' },
  { slug: 'factor', name: 'Factor Calculator', shortName: 'Factor', category: 'math', description: 'Calculate factor with explicit client-side inputs.', keywords: ['factor calculator'], icon: '∑' },
  { slug: 'matrix', name: 'Matrix Calculator', shortName: 'Matrix', category: 'math', description: 'Calculate matrix with explicit client-side inputs.', keywords: ['matrix calculator'], icon: '∑' },
  { slug: 'basic', name: 'Basic Calculator', shortName: 'Basic', category: 'math', description: 'Calculate basic with explicit client-side inputs.', keywords: ['basic calculator'], icon: '∑' },
  { slug: 'long-division', name: 'Long Division Calculator', shortName: 'Long Division', category: 'math', description: 'Calculate long division with explicit client-side inputs.', keywords: ['long-division calculator'], icon: '∑' },
  { slug: 'average', name: 'Average Calculator', shortName: 'Average', category: 'math', description: 'Calculate average with explicit client-side inputs.', keywords: ['average calculator'], icon: '∑' },
  { slug: 'p-value', name: 'P-value Calculator', shortName: 'P-value', category: 'math', description: 'Calculate p-value with explicit client-side inputs.', keywords: ['p-value calculator'], icon: '∑' },
  {
    slug: 'bmi',
    name: 'BMI Calculator',
    shortName: 'BMI',
    category: 'fitness',
    description:
      'Calculate your Body Mass Index (BMI) using metric or imperial units. Get your weight category and healthy weight range.',
    keywords: ['bmi calculator', 'body mass index', 'healthy weight', 'overweight calculator'],
    icon: '⚖️',
  },
  {
    slug: 'calorie',
    name: 'Calorie Calculator',
    shortName: 'Calorie',
    category: 'fitness',
    description:
      'Calculate your daily calorie needs using the Mifflin-St Jeor formula. Find your BMR and TDEE for weight loss or gain.',
    keywords: ['calorie calculator', 'tdee calculator', 'bmr calculator', 'daily calories'],
    icon: '🔥',
  },
  {
    slug: 'gpa',
    name: 'GPA Calculator',
    shortName: 'GPA',
    category: 'math',
    description:
      'Calculate your weighted and unweighted GPA. Supports regular, honors, and AP/IB courses on a 4.0 scale.',
    keywords: ['gpa calculator', 'grade point average', 'weighted gpa', 'ap gpa calculator'],
    icon: '🎓',
  },
  {
    slug: 'loan',
    name: 'Loan Calculator',
    shortName: 'Loan',
    category: 'financial',
    description:
      'Calculate monthly loan payments, total interest, and view a full amortization schedule for any loan amount.',
    keywords: ['loan calculator', 'loan payment calculator', 'amortization calculator', 'personal loan'],
    icon: '💰',
  },
  {
    slug: 'percentage',
    name: 'Percentage Calculator',
    shortName: 'Percentage',
    category: 'math',
    description:
      'Calculate percentages instantly. Find what % of a number is, what percent one number is of another, or % change.',
    keywords: ['percentage calculator', 'percent calculator', 'percent change calculator', 'percentage increase'],
    icon: '📊',
  },
  {
    slug: 'tip',
    name: 'Tip Calculator',
    shortName: 'Tip',
    category: 'lifestyle',
    description:
      'Calculate the tip amount and split the bill among multiple people. Works for any tip percentage.',
    keywords: ['tip calculator', 'gratuity calculator', 'bill split calculator', 'restaurant tip'],
    icon: '🍽️',
  },
  {
    slug: 'rental-property',
    name: 'Rental Property Calculator',
    shortName: 'Rental Property',
    category: 'financial',
    description:
      'Analyze a rental property investment. Calculate monthly cash flow, cash-on-cash return, cap rate, and gross rent multiplier using real expenses.',
    keywords: ['rental property calculator', 'cash on cash return', 'cap rate calculator', 'real estate investment', 'rental income calculator', 'noi calculator'],
    icon: '🏘️',
  },
  {
    slug: 'real-estate',
    name: 'Real Estate Calculator',
    shortName: 'Real Estate ROI',
    category: 'financial',
    description:
      'Calculate real estate ROI, home appreciation, equity growth, and total profit on a property sale. Includes optional rental income analysis.',
    keywords: ['real estate calculator', 'real estate roi', 'home appreciation calculator', 'property investment calculator', 'real estate profit'],
    icon: '📈',
  },
  {
    slug: 'fha-loan',
    name: 'FHA Loan Calculator',
    shortName: 'FHA Loan',
    category: 'financial',
    description:
      'Calculate FHA loan payments including upfront and annual Mortgage Insurance Premium (MIP). See the true monthly cost for low-down-payment buyers.',
    keywords: ['fha loan calculator', 'fha mortgage calculator', 'fha mip calculator', 'fha payment', 'fha mortgage insurance', '3.5 percent down payment'],
    icon: '🏛️',
  },
  {
    slug: 'va-mortgage',
    name: 'VA Mortgage Calculator',
    shortName: 'VA Mortgage',
    category: 'financial',
    description:
      'Calculate VA loan payments and funding fee for veterans and active-duty service members. No PMI required — see how much you save vs a conventional loan.',
    keywords: ['va mortgage calculator', 'va loan calculator', 'va funding fee', 'veteran home loan', 'va home loan payment', 'military mortgage'],
    icon: '🎖️',
  },
  {
    slug: 'home-equity-loan',
    name: 'Home Equity Loan Calculator',
    shortName: 'Home Equity Loan',
    category: 'financial',
    description:
      'Calculate how much you can borrow against your home equity. See monthly payments, CLTV ratio, and total cost for a fixed-rate second mortgage.',
    keywords: ['home equity loan calculator', 'heloc calculator', 'second mortgage calculator', 'home equity calculator', 'cltv calculator', 'equity loan payment'],
    icon: '🏦',
  },
  {
    slug: 'heloc',
    name: 'HELOC Calculator',
    shortName: 'HELOC',
    category: 'financial',
    description:
      'Calculate your Home Equity Line of Credit limit, draw-period interest-only payments, and repayment-period P&I payments. See CLTV, max credit line, and total interest across both phases.',
    keywords: ['heloc calculator', 'home equity line of credit', 'heloc payment', 'draw period', 'heloc interest', 'equity line calculator'],
    icon: '🏗️',
  },
  {
    slug: 'down-payment',
    name: 'Down Payment Calculator',
    shortName: 'Down Payment',
    category: 'financial',
    description:
      'Calculate how much you need for a down payment and closing costs. See PMI costs, loan-type minimums (FHA, VA, conventional), and a savings timeline to reach your goal.',
    keywords: ['down payment calculator', 'how much down payment', 'closing costs calculator', 'pmi calculator', 'down payment savings', 'fha down payment'],
    icon: '💵',
  },
  {
    slug: 'refinance',
    name: 'Refinance Calculator',
    shortName: 'Refinance',
    category: 'financial',
    description:
      'Find out if refinancing your mortgage makes sense. Compare monthly savings, break-even point, and lifetime interest savings against closing costs.',
    keywords: ['refinance calculator', 'mortgage refinance calculator', 'break even refinance', 'should i refinance', 'refi calculator', 'refinancing savings'],
    icon: '🔄',
  },
  {
    slug: 'mortgage-payoff',
    name: 'Mortgage Payoff Calculator',
    shortName: 'Payoff',
    category: 'financial',
    description:
      'See how extra monthly payments or a lump sum can accelerate your mortgage payoff. Calculate interest saved and years cut from your loan term.',
    keywords: ['mortgage payoff calculator', 'extra mortgage payment calculator', 'pay off mortgage early', 'mortgage early payoff', 'lump sum mortgage payment', 'mortgage interest savings'],
    icon: '🏁',
  },
  {
    slug: 'mortgage-uk',
    name: 'Mortgage Calculator UK',
    shortName: 'UK Mortgage',
    category: 'financial',
    description:
      'UK mortgage calculator with Stamp Duty Land Tax (SDLT), LTV, repayment vs interest-only, and arrangement fees. First-time buyer and buy-to-let rates included.',
    keywords: ['mortgage calculator uk', 'uk mortgage calculator', 'stamp duty calculator', 'sdlt calculator', 'uk home loan', 'first time buyer calculator uk', 'buy to let mortgage calculator'],
    icon: '🇬🇧',
  },
  {
    slug: 'canadian-mortgage',
    name: 'Canadian Mortgage Calculator',
    shortName: 'Canadian Mortgage',
    category: 'financial',
    description:
      'Canadian mortgage calculator with semi-annual compounding (Interest Act), CMHC mortgage insurance, monthly and accelerated bi-weekly payment options.',
    keywords: ['canadian mortgage calculator', 'canada mortgage calculator', 'cmhc calculator', 'canadian home loan', 'semi-annual compounding mortgage', 'canadian amortization', 'bi-weekly mortgage canada'],
    icon: '🇨🇦',
  },
  {
    slug: 'personal-loan',
    name: 'Personal Loan Calculator',
    shortName: 'Personal Loan',
    category: 'financial',
    description:
      'Calculate monthly payments, total interest, and true APR for any personal loan. Supports origination fees to show the real cost of borrowing.',
    keywords: ['personal loan calculator', 'personal loan payment calculator', 'loan apr calculator', 'origination fee calculator', 'unsecured loan calculator', 'personal loan interest'],
    icon: '💳',
  },
  {
    slug: 'auto-loan',
    name: 'Auto Loan Calculator',
    shortName: 'Auto Loan',
    category: 'financial',
    description:
      'Calculate monthly car loan payments including sales tax, trade-in value, dealer fees, and down payment. See the full amortization schedule.',
    keywords: ['auto loan calculator', 'car loan calculator', 'car payment calculator', 'vehicle loan calculator', 'auto loan payment', 'car financing calculator'],
    icon: '🚗',
  },
  {
    slug: 'auto-lease',
    name: 'Auto Lease Calculator',
    shortName: 'Auto Lease',
    category: 'financial',
    description:
      'Calculate monthly car lease payments using money factor, residual value, and cap cost. Understand depreciation, finance charges, and total lease cost.',
    keywords: ['auto lease calculator', 'car lease calculator', 'lease payment calculator', 'money factor calculator', 'residual value calculator', 'cap cost calculator', 'lease vs buy calculator'],
    icon: '🔑',
  },
  {
    slug: 'boat-loan',
    name: 'Boat Loan Calculator',
    shortName: 'Boat Loan',
    category: 'financial',
    description:
      'Estimate boat loan payments, total interest, financed amount, taxes, fees, and yearly amortization from your purchase price and loan terms.',
    keywords: ['boat loan calculator', 'boat payment calculator', 'marine loan calculator', 'boat financing calculator', 'boat loan payment', 'boat interest calculator'],
    icon: '⛵',
  },
  {
    slug: 'payment',
    name: 'Payment Calculator',
    shortName: 'Payment',
    category: 'financial',
    description:
      'Calculate a fixed-rate loan payment, total interest, total cost, and amortization schedule from the amount, rate, term, and fees.',
    keywords: ['payment calculator', 'loan payment calculator', 'monthly payment calculator', 'fixed payment calculator', 'finance payment calculator'],
    icon: '🧾',
  },
  {
    slug: 'repayment',
    name: 'Repayment Calculator',
    shortName: 'Repayment',
    category: 'financial',
    description:
      'Find how many payments you need to clear a balance from your interest rate and planned monthly repayment, with a warning when payment is too low.',
    keywords: ['repayment calculator', 'debt repayment calculator', 'loan repayment calculator', 'payoff calculator', 'monthly repayment calculator'],
    icon: '🔁',
  },
  {
    slug: 'student-loan',
    name: 'Student Loan Calculator',
    shortName: 'Student Loan',
    category: 'financial',
    description:
      'Estimate student loan payments, origination fees, total interest, payoff time, and savings from an extra monthly payment.',
    keywords: ['student loan calculator', 'student loan payment calculator', 'college loan calculator', 'student debt calculator', 'student loan interest calculator'],
    icon: '🎓',
  },
  {
    slug: 'college-cost',
    name: 'College Cost Calculator',
    shortName: 'College Cost',
    category: 'financial',
    description:
      'Project future annual and four-year college costs with inflation, then compare them with current savings and growing annual contributions.',
    keywords: ['college cost calculator', 'college tuition calculator', 'future college cost calculator', 'education savings calculator', 'college savings calculator'],
    icon: '🏫',
  },
  { slug: 'credit-utilization', name: 'Credit Utilization Calculator', shortName: 'Credit Utilization', category: 'financial', description: 'Calculate revolving balance as a percentage of available credit.', keywords: ['credit utilization calculator','credit card utilization ratio'], icon: '📊' },
  { slug: 'debt-snowball', name: 'Debt Snowball Calculator', shortName: 'Debt Snowball', category: 'financial', description: 'Order debts from smallest balance to largest for a payoff strategy estimate.', keywords: ['debt snowball calculator','snowball debt payoff'], icon: '❄️' },
  { slug: 'debt-avalanche', name: 'Debt Avalanche Calculator', shortName: 'Debt Avalanche', category: 'financial', description: 'Order debts from highest APR to lowest for a payoff strategy estimate.', keywords: ['debt avalanche calculator','avalanche debt payoff'], icon: '📉' },
  { slug: 'amortization', name: 'Amortization Calculator', shortName: 'Amortization', category: 'financial', description: 'Calculate fixed loan payment, total interest, and total cost.', keywords: ['amortization calculator','loan amortization'], icon: '📅' },
  { slug: 'bond', name: 'Bond Calculator', shortName: 'Bond', category: 'financial', description: 'Estimate a coupon bond price from face value, coupon rate, yield, and term.', keywords: ['bond calculator','bond price calculator'], icon: '📜' },
  { slug: 'mutual-fund', name: 'Mutual Fund Calculator', shortName: 'Mutual Fund', category: 'financial', description: 'Project mutual-fund value with contributions, return, and expense ratio.', keywords: ['mutual fund calculator','fund growth calculator'], icon: '📈' },
  {
    slug: 'credit-card',
    name: 'Credit Card Calculator',
    shortName: 'Credit Card',
    category: 'financial',
    description: 'Estimate a credit-card minimum payment, payoff time, total payments, and interest from balance and APR.',
    keywords: ['credit card calculator', 'credit card payment calculator', 'credit card interest calculator', 'minimum payment calculator', 'credit card payoff time'],
    icon: '💳',
  },
  {
    slug: 'credit-cards-payoff',
    name: 'Credit Cards Payoff Calculator',
    shortName: 'Credit Cards Payoff',
    category: 'financial',
    description: 'Combine three card balances and payment assumptions to estimate total interest and the longest payoff period.',
    keywords: ['credit cards payoff calculator', 'multiple credit card payoff calculator', 'credit card debt payoff', 'pay off multiple credit cards'],
    icon: '💳',
  },
  {
    slug: 'debt-payoff',
    name: 'Debt Payoff Calculator',
    shortName: 'Debt Payoff',
    category: 'financial',
    description: 'Estimate debt payoff months, total interest, and total payments from a balance, APR, and planned monthly payment.',
    keywords: ['debt payoff calculator', 'debt payment calculator', 'payoff time calculator', 'debt interest calculator'],
    icon: '📉',
  },
  {
    slug: 'debt-consolidation',
    name: 'Debt Consolidation Calculator',
    shortName: 'Debt Consolidation',
    category: 'financial',
    description: 'Compare an existing debt payment and interest with a new fixed-rate consolidation payment, fees, and term.',
    keywords: ['debt consolidation calculator', 'consolidation loan calculator', 'debt refinance calculator', 'debt consolidation savings'],
    icon: '🔗',
  },
  {
    slug: 'debt-to-income',
    name: 'Debt-to-Income Ratio Calculator',
    shortName: 'Debt-to-Income Ratio',
    category: 'financial',
    description: 'Calculate current and proposed debt-to-income ratios from gross monthly income, debts, housing, and new debt.',
    keywords: ['debt to income ratio calculator', 'DTI calculator', 'debt-to-income calculator', 'monthly debt ratio'],
    icon: '⚖️',
  },
  { slug: 'cash-back-low-interest', name: 'Cash Back or Low Interest Calculator', shortName: 'Cash Back or Low Interest', category: 'financial', description: 'Compare a cash-back option with a low-interest option over a selected term.', keywords: ['cash back or low interest calculator', 'cash back calculator', 'low interest calculator'], icon: '💸' },
  { slug: 'interest', name: 'Interest Calculator', shortName: 'Interest', category: 'financial', description: 'Calculate simple interest and total value from principal, rate, and time.', keywords: ['interest calculator', 'interest earned calculator', 'interest formula calculator'], icon: '📈' },
  { slug: 'simple-interest', name: 'Simple Interest Calculator', shortName: 'Simple Interest', category: 'financial', description: 'Calculate simple interest using principal, annual rate, and years.', keywords: ['simple interest calculator', 'simple interest formula', 'simple interest rate calculator'], icon: '➕' },
  { slug: 'compound-interest', name: 'Compound Interest Calculator', shortName: 'Compound Interest', category: 'financial', description: 'Project compound growth with compounding frequency and recurring contributions.', keywords: ['compound interest calculator', 'compound growth calculator', 'investment compound interest'], icon: '📊' },
  { slug: 'interest-rate', name: 'Interest Rate Calculator', shortName: 'Interest Rate', category: 'financial', description: 'Solve the annual compound rate required to grow a principal to a final value.', keywords: ['interest rate calculator', 'required rate calculator', 'annual interest rate calculator'], icon: '％' },
  { slug: 'investment', name: 'Investment Calculator', shortName: 'Investment', category: 'financial', description: 'Project future investment value from starting balance, contributions, return, and time.', keywords: ['investment calculator', 'investment return calculator', 'future investment value'], icon: '💼' },
  { slug: 'retirement', name: 'Retirement Calculator', shortName: 'Retirement', category: 'financial', description: 'Project retirement savings from current balance, contributions, employer contribution, return, and years.', keywords: ['retirement calculator', 'retirement savings calculator', 'retirement planning calculator'], icon: '🏖️' },
  { slug: '401k', name: '401K Calculator', shortName: '401K', category: 'financial', description: 'Project 401K value with monthly contributions and an employer match assumption.', keywords: ['401k calculator', '401k contribution calculator', '401k retirement calculator'], icon: '🏦' },
  { slug: 'roth-ira', name: 'Roth IRA Calculator', shortName: 'Roth IRA', category: 'financial', description: 'Project Roth IRA value from current balance, monthly contribution, return, and years.', keywords: ['roth ira calculator', 'roth ira contribution calculator', 'roth ira growth calculator'], icon: '📌' },
  { slug: 'ira', name: 'IRA Calculator', shortName: 'IRA', category: 'financial', description: 'Project IRA value from current balance, monthly contribution, return, and years.', keywords: ['ira calculator', 'ira growth calculator', 'ira contribution calculator'], icon: '📚' },
  { slug: 'rmd', name: 'RMD Calculator', shortName: 'RMD', category: 'financial', description: 'Estimate a required minimum distribution from a retirement balance and divisor.', keywords: ['rmd calculator', 'required minimum distribution calculator', 'retirement distribution calculator'], icon: '📋' },
  { slug: 'annuity', name: 'Annuity Calculator', shortName: 'Annuity', category: 'financial', description: 'Estimate periodic annuity payment, total payments, and interest.', keywords: ['annuity calculator', 'annuity payment calculator', 'annuity interest calculator'], icon: '🔄' },
  { slug: 'annuity-payout', name: 'Annuity Payout Calculator', shortName: 'Annuity Payout', category: 'financial', description: 'Estimate a periodic payout from an annuity balance, rate, and term.', keywords: ['annuity payout calculator', 'annuity income calculator', 'annuity withdrawal calculator'], icon: '💰' },
  { slug: 'savings', name: 'Savings Calculator', shortName: 'Savings', category: 'financial', description: 'Project savings growth with starting balance, monthly contributions, rate, and time.', keywords: ['savings calculator', 'savings interest calculator', 'savings growth calculator'], icon: '🐖' },
  { slug: 'cd', name: 'CD Calculator', shortName: 'CD', category: 'financial', description: 'Estimate certificate of deposit growth from principal, rate, and term.', keywords: ['cd calculator', 'certificate of deposit calculator', 'cd interest calculator'], icon: '🏛️' },
  { slug: 'income-tax', name: 'Income Tax Calculator', shortName: 'Income Tax', category: 'financial', description: 'Estimate income tax from amount and tax-rate assumption.', keywords: ['income tax calculator','income tax estimate'], icon: '🧾' },
  { slug: 'salary', name: 'Salary Calculator', shortName: 'Salary', category: 'financial', description: 'Estimate salary after a tax-rate assumption.', keywords: ['salary calculator','salary after tax'], icon: '💼' },
  { slug: 'take-home-paycheck', name: 'Take-Home-Paycheck Calculator', shortName: 'Take Home Paycheck', category: 'financial', description: 'Estimate take-home amount from gross pay and tax-rate assumption.', keywords: ['take home paycheck calculator','paycheck calculator'], icon: '💵' },
  { slug: 'sales-tax', name: 'Sales Tax Calculator', shortName: 'Sales Tax', category: 'financial', description: 'Calculate sales tax and total purchase amount.', keywords: ['sales tax calculator','tax calculator'], icon: '🛒' },
  { slug: 'marriage-tax', name: 'Marriage Tax Calculator', shortName: 'Marriage Tax', category: 'financial', description: 'Estimate combined tax from two incomes and a shared rate assumption.', keywords: ['marriage tax calculator','married tax calculator'], icon: '💍' },
  { slug: 'inflation', name: 'Inflation Calculator', shortName: 'Inflation', category: 'financial', description: 'Estimate future value after inflation.', keywords: ['inflation calculator','inflation rate calculator'], icon: '📈' },
  { slug: 'depreciation', name: 'Depreciation Calculator', shortName: 'Depreciation', category: 'financial', description: 'Estimate declining book value.', keywords: ['depreciation calculator','asset depreciation calculator'], icon: '📉' },
  { slug: 'average-return', name: 'Average Return Calculator', shortName: 'Average Return', category: 'financial', description: 'Estimate annualized return.', keywords: ['average return calculator','annualized return calculator'], icon: '📊' },
  { slug: 'margin', name: 'Margin Calculator', shortName: 'Margin', category: 'financial', description: 'Calculate margin from revenue and cost.', keywords: ['margin calculator','profit margin calculator'], icon: '📐' },
  { slug: 'discount', name: 'Discount Calculator', shortName: 'Discount', category: 'financial', description: 'Calculate sale price and discount savings.', keywords: ['discount calculator','sale price calculator'], icon: '🏷️' },
  { slug: 'percent-off', name: 'Percent Off Calculator', shortName: 'Percent Off', category: 'financial', description: 'Calculate sale price after a percentage discount.', keywords: ['percent off calculator','discount percentage calculator'], icon: '🏷️' },
  { slug: 'business-loan', name: 'Business Loan Calculator', shortName: 'Business Loan', category: 'financial', description: 'Estimate business loan payments.', keywords: ['business loan calculator','commercial loan calculator'], icon: '🏢' },
  { slug: 'lease', name: 'Lease Calculator', shortName: 'Lease', category: 'financial', description: 'Estimate lease payments.', keywords: ['lease calculator','lease payment calculator'], icon: '🔑' },
  { slug: 'budget', name: 'Budget Calculator', shortName: 'Budget', category: 'financial', description: 'Calculate remaining budget after costs.', keywords: ['budget calculator','budget planner'], icon: '📒' },
  { slug: 'irr', name: 'IRR Calculator', shortName: 'IRR', category: 'financial', description: 'Estimate an annualized internal rate of return.', keywords: ['irr calculator','internal rate of return calculator'], icon: '📈' },
  { slug: 'roi', name: 'ROI Calculator', shortName: 'ROI', category: 'financial', description: 'Calculate return on investment.', keywords: ['roi calculator','return on investment calculator'], icon: '📈' },
  { slug: 'apr', name: 'APR Calculator', shortName: 'APR', category: 'financial', description: 'Estimate annual percentage rate.', keywords: ['apr calculator','annual percentage rate calculator'], icon: '💳' },
  { slug: 'payback-period', name: 'Payback Period Calculator', shortName: 'Payback Period', category: 'financial', description: 'Estimate time to recover an investment.', keywords: ['payback period calculator','investment payback calculator'], icon: '⏱️' },
  { slug: 'present-value', name: 'Present Value Calculator', shortName: 'Present Value', category: 'financial', description: 'Calculate present value from future value and rate.', keywords: ['present value calculator','pv calculator'], icon: '💰' },
  { slug: 'future-value', name: 'Future Value Calculator', shortName: 'Future Value', category: 'financial', description: 'Calculate future value from principal and rate.', keywords: ['future value calculator','fv calculator'], icon: '🔮' },
  { slug: 'estate-tax', name: 'Estate Tax Calculator', shortName: 'Estate Tax', category: 'financial', description: 'Estimate taxable estate and estate tax from an exemption and tax-rate assumption.', keywords: ['estate tax calculator','inheritance tax calculator','taxable estate'], icon: '🏛️' },
  { slug: 'finance', name: 'Finance Calculator', shortName: 'Finance', category: 'financial', description: 'Calculate a fixed-rate finance payment and total interest.', keywords: ['finance calculator','loan finance calculator','payment finance'], icon: '💼' },
  { slug: 'pension', name: 'Pension Calculator', shortName: 'Pension', category: 'financial', description: 'Project a pension fund from current savings, contributions, return, and years.', keywords: ['pension calculator','pension fund calculator','retirement pension'], icon: '🧓' },
  { slug: 'social-security', name: 'Social Security Calculator', shortName: 'Social Security', category: 'financial', description: 'Estimate a monthly benefit from average earnings, a cap, and a replacement-rate assumption.', keywords: ['social security calculator','social security benefits calculator','retirement benefit'], icon: '🛡️' },
  { slug: 'currency', name: 'Currency Calculator', shortName: 'Currency', category: 'financial', description: 'Convert an amount using a user-supplied exchange rate.', keywords: ['currency calculator','currency converter','exchange rate calculator'], icon: '💱' },
  { slug: 'commission', name: 'Commission Calculator', shortName: 'Commission', category: 'financial', description: 'Calculate sales commission and total earnings from a base amount and commission rate.', keywords: ['commission calculator','sales commission calculator','commission rate'], icon: '💼' },
  { slug: 'vat', name: 'VAT Calculator', shortName: 'VAT', category: 'financial', description: 'Calculate VAT amount and total price from a base amount and VAT rate.', keywords: ['vat calculator','value added tax calculator','vat rate'], icon: '🧾' },
  { slug: 'anorexic-bmi', name: 'Anorexic BMI Calculator', shortName: 'Anorexic BMI', category: 'fitness', description: 'Calculate BMI and flag values below the standard underweight threshold; it is not a diagnosis.', keywords: ['anorexic bmi calculator','low bmi calculator','bmi underweight'], icon: '⚖️' },
  { slug: 'bmr', name: 'BMR Calculator', shortName: 'BMR', category: 'fitness', description: 'Estimate basal metabolic rate with the Mifflin-St Jeor equation.', keywords: ['bmr calculator','basal metabolic rate calculator','resting calorie calculator'], icon: '🔥' },
  { slug: 'tdee', name: 'TDEE Calculator', shortName: 'TDEE', category: 'fitness', description: 'Estimate total daily energy expenditure from BMR and an activity multiplier.', keywords: ['tdee calculator','total daily energy expenditure','maintenance calories'], icon: '⚡' },
  { slug: 'macro', name: 'Macro Calculator', shortName: 'Macro', category: 'fitness', description: 'Estimate daily carbohydrate and fat gram targets from calorie and macro assumptions.', keywords: ['macro calculator','macronutrient calculator','calorie macros'], icon: '🥗' },
  { slug: 'protein', name: 'Protein Calculator', shortName: 'Protein', category: 'fitness', description: 'Estimate daily protein grams from body weight and a grams-per-kilogram target.', keywords: ['protein calculator','daily protein calculator','protein grams'], icon: '💪' },
  { slug: 'carbohydrate', name: 'Carbohydrate Calculator', shortName: 'Carbohydrate', category: 'fitness', description: 'Estimate carbohydrate grams from daily calories and a carbohydrate share.', keywords: ['carbohydrate calculator','carb calculator','daily carbs'], icon: '🍞' },
  { slug: 'fat-intake', name: 'Fat Intake Calculator', shortName: 'Fat Intake', category: 'fitness', description: 'Estimate daily fat grams from a calorie target and fat-share range.', keywords: ['fat intake calculator','daily fat grams','dietary fat calculator'], icon: '🥑' },
  { slug: 'ideal-weight', name: 'Ideal Weight Calculator', shortName: 'Ideal Weight', category: 'fitness', description: 'Estimate a reference weight from height using a BMI-based midpoint.', keywords: ['ideal weight calculator','ideal body weight calculator','height weight calculator'], icon: '⚖️' },
  { slug: 'healthy-weight', name: 'Healthy Weight Calculator', shortName: 'Healthy Weight', category: 'fitness', description: 'Estimate a BMI-based healthy weight range from height.', keywords: ['healthy weight calculator','healthy weight range','weight range calculator'], icon: '✅' },
  { slug: 'lean-body-mass', name: 'Lean Body Mass Calculator', shortName: 'Lean Body Mass', category: 'fitness', description: 'Estimate lean body mass from weight and height using a validated population formula.', keywords: ['lean body mass calculator','lbm calculator','lean mass'], icon: '💪' },
  { slug: 'calories-burned', name: 'Calories Burned Calculator', shortName: 'Calories Burned', category: 'fitness', description: 'Estimate calories burned from body weight, MET, and exercise duration assumptions.', keywords: ['calories burned calculator','exercise calorie calculator','met calculator'], icon: '🏃' },
  { slug: 'target-heart-rate', name: 'Target Heart Rate Calculator', shortName: 'Target Heart Rate', category: 'fitness', description: 'Estimate a maximum heart-rate reference from age.', keywords: ['target heart rate calculator','heart rate zones','max heart rate'], icon: '❤️' },
  { slug: 'one-rep-max', name: 'One Rep Max Calculator', shortName: 'One Rep Max', category: 'fitness', description: 'Estimate one-repetition maximum from a lifted load and repetitions.', keywords: ['one rep max calculator','1rm calculator','strength calculator'], icon: '🏋️' },
  { slug: 'weight-watcher-points', name: 'Weight Watcher Points Calculator', shortName: 'Weight Watcher Points', category: 'fitness', description: 'Estimate a simplified points score from entered nutrition and body inputs.', keywords: ['weight watcher points calculator','points calculator','diet points'], icon: '📊' },
  { slug: 'overweight', name: 'Overweight Calculator', shortName: 'Overweight', category: 'fitness', description: 'Calculate BMI and compare it with an overweight reference threshold.', keywords: ['overweight calculator','overweight bmi calculator','bmi threshold'], icon: '⚖️' },
  { slug: 'body-fat', name: 'Body Fat Calculator', shortName: 'Body Fat', category: 'fitness', description: 'Estimate body-fat percentage from entered body measurements.', keywords: ['body fat calculator','body fat percentage','fitness body composition'], icon: '📏' },
  { slug: 'army-body-fat', name: 'Army Body Fat Calculator', shortName: 'Army Body Fat', category: 'fitness', description: 'Estimate body-fat percentage from body measurements using a screening equation.', keywords: ['army body fat calculator','military body fat calculator','body fat tape test'], icon: '🎖️' },
  { slug: 'body-surface-area', name: 'Body Surface Area Calculator', shortName: 'Body Surface Area', category: 'fitness', description: 'Estimate body surface area from height and weight.', keywords: ['body surface area calculator','bsa calculator','mosteller formula'], icon: '📐' },
  { slug: 'body-type', name: 'Body Type Calculator', shortName: 'Body Type', category: 'fitness', description: 'Classify a BMI-based body type for educational screening.', keywords: ['body type calculator','somatotype calculator','bmi type'], icon: '🧍' },
  { slug: 'pregnancy', name: 'Pregnancy Calculator', shortName: 'Pregnancy', category: 'fitness', description: 'Estimate weeks remaining from a pregnancy-week input.', keywords: ['pregnancy calculator','pregnancy weeks calculator','gestation calculator'], icon: '🤰' },
  { slug: 'pregnancy-weight-gain', name: 'Pregnancy Weight Gain Calculator', shortName: 'Pregnancy Weight Gain', category: 'fitness', description: 'Estimate a simplified pregnancy weight-gain range by pregnancy week.', keywords: ['pregnancy weight gain calculator','pregnancy weight chart','gestational weight gain'], icon: '⚖️' },
  { slug: 'pregnancy-conception', name: 'Pregnancy Conception Calculator', shortName: 'Pregnancy Conception', category: 'fitness', description: 'Estimate pregnancy timing from cycle and gestational assumptions.', keywords: ['pregnancy conception calculator','conception date calculator'], icon: '🤰' },
  { slug: 'due-date', name: 'Due Date Calculator', shortName: 'Due Date', category: 'fitness', description: 'Estimate pregnancy timing and remaining days from completed weeks.', keywords: ['due date calculator','pregnancy due date'], icon: '📅' },
  { slug: 'ovulation', name: 'Ovulation Calculator', shortName: 'Ovulation', category: 'fitness', description: 'Estimate ovulation cycle day from cycle length.', keywords: ['ovulation calculator','ovulation date calculator'], icon: '🗓️' },
  { slug: 'conception', name: 'Conception Calculator', shortName: 'Conception', category: 'fitness', description: 'Estimate a conception timing window from cycle inputs.', keywords: ['conception calculator','conception date'], icon: '🌱' },
  { slug: 'period', name: 'Period Calculator', shortName: 'Period', category: 'fitness', description: 'Estimate the next cycle day from cycle length.', keywords: ['period calculator','next period calculator','menstrual cycle calculator'], icon: '🩸' },
  { slug: 'scientific-notation', name: 'Scientific Notation Calculator', shortName: 'Scientific Notation', category: 'math', description: 'Convert a number to normalized scientific notation with a coefficient and base-10 exponent.', keywords: ['scientific notation calculator','standard form calculator','exponent notation'], icon: '×10' },
  { slug: 'big-number', name: 'Big Number Calculator', shortName: 'Big Number', category: 'math', description: 'Add arbitrarily large whole numbers without losing integer precision in the browser.', keywords: ['big number calculator','large number addition','arbitrary precision calculator'], icon: '∞' },
  { slug: 'common-factor', name: 'Common Factor Calculator', shortName: 'Common Factor', category: 'math', description: 'List the positive integer factors shared by two whole numbers.', keywords: ['common factor calculator','common factors','shared factors'], icon: '∩' },
  { slug: 'date', name: 'Date Calculator', shortName: 'Date', category: 'lifestyle', description: 'Add or subtract a whole number of calendar days from a chosen date.', keywords: ['date calculator','add days to date','days from date'], icon: '📅' },
  { slug: 'time', name: 'Time Calculator', shortName: 'Time', category: 'lifestyle', description: 'Find the elapsed time in minutes between two clock times.', keywords: ['time calculator','time duration calculator','elapsed time'], icon: '⏱️' },
  { slug: 'hours', name: 'Hours Calculator', shortName: 'Hours', category: 'lifestyle', description: 'Estimate net paid hours from a same-day shift and unpaid break.', keywords: ['hours calculator','work hours calculator','hours worked'], icon: '⌚' },
  { slug: 'grade', name: 'Grade Calculator', shortName: 'Grade', category: 'math', description: 'Convert points earned out of points possible into a percentage and simple letter band.', keywords: ['grade calculator','percentage grade calculator','letter grade calculator'], icon: '🎓' },
  { slug: 'height', name: 'Height Calculator', shortName: 'Height', category: 'lifestyle', description: 'Convert feet and inches into total inches, centimeters, and meters.', keywords: ['height calculator','feet to cm','feet and inches converter'], icon: '📏' },
  { slug: 'concrete', name: 'Concrete Calculator', shortName: 'Concrete', category: 'lifestyle', description: 'Estimate rectangular concrete volume in cubic feet and cubic yards from dimensions.', keywords: ['concrete calculator','concrete volume calculator','cubic yards concrete'], icon: '🧱' },
  { slug: 'ip-subnet', name: 'IP Subnet Calculator', shortName: 'IP Subnet', category: 'math', description: 'Calculate IPv4 network, broadcast, host range, and address capacity from CIDR notation.', keywords: ['ip subnet calculator','cidr calculator','ipv4 subnet calculator'], icon: '🌐' },
  { slug: 'conversion', name: 'Conversion Calculator', shortName: 'Conversion', category: 'math', description: 'Convert length values between metric and imperial units with explicit source and target labels.', keywords: ['conversion calculator','unit conversion calculator','length converter'], icon: '⇄' },
  { slug: 'fuel-cost', name: 'Fuel Cost Calculator', shortName: 'Fuel Cost', category: 'lifestyle', description: 'Estimate trip fuel use and cost from distance, fuel economy, and price per gallon.', keywords: ['fuel cost calculator','road trip fuel calculator','gas cost calculator'], icon: '⛽' },
  { slug: 'voltage-drop', name: 'Voltage Drop Calculator', shortName: 'Voltage Drop', category: 'lifestyle', description: 'Estimate round-trip voltage drop and remaining voltage from current, length, resistance, and supply.', keywords: ['voltage drop calculator','wire voltage drop','cable voltage loss'], icon: '⚡' },
  { slug: 'btu', name: 'BTU Calculator', shortName: 'BTU', category: 'lifestyle', description: 'Estimate a simplified heating load from area, temperature difference, and heat-loss factor.', keywords: ['btu calculator','heating load calculator','btu per hour calculator'], icon: '♨️' },
  { slug: 'square-footage', name: 'Square Footage Calculator', shortName: 'Square Footage', category: 'lifestyle', description: 'Calculate rectangular area in square feet from length and width.', keywords: ['square footage calculator','square feet calculator','room area calculator'], icon: '▧' },
  { slug: 'time-card', name: 'Time Card Calculator', shortName: 'Time Card', category: 'lifestyle', description: 'Estimate regular hours, overtime hours, and gross pay from a simple work schedule.', keywords: ['time card calculator','timesheet calculator','overtime hours calculator'], icon: '🗂️' },
  { slug: 'time-zone', name: 'Time Zone Calculator', shortName: 'Time Zone', category: 'lifestyle', description: 'Format a UTC instant in a selected IANA time zone with daylight-saving rules.', keywords: ['time zone calculator','timezone converter','world clock conversion'], icon: '🌍' },
  { slug: 'sleep', name: 'Sleep Calculator', shortName: 'Sleep', category: 'lifestyle', description: 'Estimate sleep duration between bedtime and wake time, including overnight intervals.', keywords: ['sleep calculator','sleep duration calculator','hours of sleep'], icon: '☾' },
  { slug: 'roofing', name: 'Roofing Calculator', shortName: 'Roofing', category: 'lifestyle', description: 'Estimate pitched roof area and an order area with an explicit waste allowance.', keywords: ['roofing calculator','roof area calculator','roofing materials estimate'], icon: '⌂' },
  { slug: 'tile', name: 'Tile Calculator', shortName: 'Tile', category: 'lifestyle', description: 'Estimate tile count for a rectangular floor using tile dimensions and waste.', keywords: ['tile calculator','tile quantity calculator','floor tile estimator'], icon: '▦' },
  { slug: 'mulch', name: 'Mulch Calculator', shortName: 'Mulch', category: 'lifestyle', description: 'Estimate mulch volume in cubic yards from area and depth.', keywords: ['mulch calculator','mulch yard calculator','landscaping mulch estimate'], icon: '♧' },
  { slug: 'gravel', name: 'Gravel Calculator', shortName: 'Gravel', category: 'lifestyle', description: 'Estimate gravel volume in cubic yards from area and depth.', keywords: ['gravel calculator','gravel yard calculator','landscaping gravel estimate'], icon: '◇' },
  { slug: 'wind-chill', name: 'Wind Chill Calculator', shortName: 'Wind Chill', category: 'lifestyle', description: 'Estimate apparent cold from air temperature and wind speed using the common wind-chill formula.', keywords: ['wind chill calculator','wind chill index','apparent temperature cold'], icon: '❄️' },
  { slug: 'heat-index', name: 'Heat Index Calculator', shortName: 'Heat Index', category: 'lifestyle', description: 'Estimate apparent heat from air temperature and relative humidity.', keywords: ['heat index calculator','feels like temperature','humidity heat calculator'], icon: '☀️' },
  { slug: 'dew-point', name: 'Dew Point Calculator', shortName: 'Dew Point', category: 'lifestyle', description: 'Estimate dew point from Celsius air temperature and relative humidity.', keywords: ['dew point calculator','humidity dew point','condensation temperature'], icon: '💧' },
  { slug: 'bandwidth', name: 'Bandwidth Calculator', shortName: 'Bandwidth', category: 'math', description: 'Convert transferred megabytes and elapsed seconds into average throughput.', keywords: ['bandwidth calculator','mbps calculator','data transfer rate'], icon: '⇄' },
  { slug: 'base64-encode-decode', name: 'Base64 Encode / Decode', shortName: 'Base64', category: 'math', description: 'Encode or decode UTF-8 text using standard Base64 representation.', keywords: ['base64 encode decode','base64 converter','text base64'], icon: '64' },
  { slug: 'url-encode-decode', name: 'URL Encode / Decode', shortName: 'URL Encode', category: 'math', description: 'Encode or decode URI component text with percent escapes.', keywords: ['url encode decode','url encoder','percent encoding'], icon: '%' },
  { slug: 'time-duration', name: 'Time Duration Calculator', shortName: 'Time Duration', category: 'lifestyle', description: 'Normalize hours, minutes, and seconds into a single elapsed duration.', keywords: ['time duration calculator','hours minutes seconds','duration converter'], icon: '◷' },
  { slug: 'day-of-the-week', name: 'Day of the Week Calculator', shortName: 'Day of the Week', category: 'lifestyle', description: 'Find the weekday for a valid ISO calendar date.', keywords: ['day of the week calculator','weekday calculator','date weekday'], icon: '▣' },
  { slug: 'random-number', name: 'Random Number Generator', shortName: 'Random Number', category: 'math', description: 'Generate repeatable or fresh integer sequences within an inclusive range, with duplicate and sort controls.', keywords: ['random number generator','seeded random number generator','random integers in range','random number list without repeats'], icon: '⤨' },
  { slug: 'password', name: 'Password Generator', shortName: 'Password Generator', category: 'lifestyle', description: 'Create browser-generated passwords with configurable character groups and an entropy estimate.', keywords: ['password generator','secure password generator','random password generator','password entropy calculator'], icon: '⌘' },
  { slug: 'dice-roller', name: 'Dice Roller', shortName: 'Dice Roller', category: 'lifestyle', description: 'Simulate one or more dice with configurable side counts and show each roll, total, and expected average.', keywords: ['dice roller','online dice roller','d20 dice roller','custom sided dice roller'], icon: '⚄' },
  { slug: 'shoe-size', name: 'Shoe Size Conversion', shortName: 'Shoe Size', category: 'lifestyle', description: 'Estimate shoe sizes across US, UK, EU, Japan, Mexico, and China from foot length and age group.', keywords: ['shoe size conversion','foot length to shoe size','US UK EU shoe size chart','kids shoe size converter'], icon: '⌁' },
  { slug: 'day-counter', name: 'Day Counter', shortName: 'Day Counter', category: 'lifestyle', description: 'Count calendar days, weekdays, weekends, and entered holidays between dates, or add business days to a date.', keywords: ['day counter','days between dates calculator','business days calculator','working days between dates'], icon: '▦' },
  { slug: 'days-until', name: 'Days Until Calculator', shortName: 'Days Until', category: 'lifestyle', description: 'Count days until or since a date with weeks, calendar breakdown, weekdays, and weekend totals.', keywords: ['days until calculator','days since calculator','countdown to date calculator','weeks and days between dates'], icon: '⌛' },
  { slug: 'emergency-fund', name: 'Emergency Fund Calculator', shortName: 'Emergency Fund', category: 'financial', description: 'Estimate a cash reserve target, savings gap, months to goal, and current expense coverage.', keywords: ['emergency fund calculator','emergency savings target','how much emergency fund do I need','months of expenses calculator'], icon: '🛟' },
  { slug: 'cagr', name: 'CAGR Calculator', shortName: 'CAGR', category: 'financial', description: 'Calculate compound annual growth rate or solve for future value and initial value over a period.', keywords: ['CAGR calculator','compound annual growth rate calculator','annualized investment growth','future value from CAGR'], icon: '↗' },
  { slug: 'loan-to-value', name: 'Loan-to-Value Calculator', shortName: 'Loan to Value', category: 'financial', description: 'Calculate LTV, estimated equity, equity percentage, and an educational combined LTV with a second lien.', keywords: ['loan to value calculator','LTV ratio calculator','home equity percentage calculator','combined loan to value calculator'], icon: '⌂' },
  { slug: 'bill-split', name: 'Bill Split Calculator', shortName: 'Bill Split', category: 'lifestyle', description: 'Split a bill equally after applying a tip percentage and a fixed service charge.', keywords: ['bill split calculator','split bill with tip','restaurant bill calculator','tip and service charge calculator'], icon: '÷' },
  { slug: 'bra-size', name: 'Bra Size Calculator', shortName: 'Bra Size', category: 'lifestyle', description: 'Estimate a starting band and cup label from underbust and bust measurements.', keywords: ['bra size calculator','bra measurement calculator','cup size calculator'], icon: '◉' },
  { slug: 'love', name: 'Love Calculator', shortName: 'Love', category: 'lifestyle', description: 'Generate a repeatable entertainment-only name score with a clear non-predictive disclaimer.', keywords: ['love calculator','compatibility calculator','love match game'], icon: '♡' },
  { slug: 'gdp', name: 'GDP Calculator', shortName: 'GDP', category: 'math', description: 'Estimate GDP using consumer spending, investment, government spending, exports, and imports.', keywords: ['gdp calculator','gross domestic product calculator','expenditure approach gdp'], icon: '∑' },
  { slug: 'gas-mileage', name: 'Gas Mileage Calculator', shortName: 'Gas Mileage', category: 'lifestyle', description: 'Calculate observed miles per gallon from trip distance and fuel used.', keywords: ['gas mileage calculator','mpg calculator','fuel economy calculator'], icon: '⛽' },
  { slug: 'horsepower', name: 'Horsepower Calculator', shortName: 'Horsepower', category: 'math', description: 'Convert watts to named mechanical and electrical horsepower conventions.', keywords: ['horsepower calculator','watts to horsepower','power conversion'], icon: '⚙️' },
  { slug: 'engine-horsepower', name: 'Engine Horsepower Calculator', shortName: 'Engine Horsepower', category: 'lifestyle', description: 'Estimate engine horsepower from torque in lb-ft and rotational speed in RPM.', keywords: ['engine horsepower calculator','torque rpm horsepower','car horsepower formula'], icon: '🏎️' },
  { slug: 'stair', name: 'Stair Calculator', shortName: 'Stair', category: 'lifestyle', description: 'Estimate riser count, tread count, run, and angle for a simple straight stair layout.', keywords: ['stair calculator','stair rise run calculator','stair stringer calculator'], icon: '🪜' },
  { slug: 'resistor', name: 'Resistor Calculator', shortName: 'Resistor', category: 'math', description: 'Calculate nominal resistance and tolerance range from two digits, a multiplier, and tolerance.', keywords: ['resistor calculator','resistance color code calculator','resistor value calculator'], icon: '▤' },
  { slug: 'ohms-law', name: 'Ohm’s Law Calculator', shortName: 'Ohm’s Law', category: 'math', description: 'Calculate resistance and power from entered voltage and current.', keywords: ['ohms law calculator','voltage current resistance calculator','electrical power calculator'], icon: 'Ω' },
  { slug: 'electricity', name: 'Electricity Calculator', shortName: 'Electricity', category: 'lifestyle', description: 'Estimate energy use and cost from appliance power, usage time, and electricity price.', keywords: ['electricity calculator','energy cost calculator','appliance electricity cost'], icon: '🔌' },
  { slug: 'mileage', name: 'Mileage Calculator', shortName: 'Mileage', category: 'lifestyle', description: 'Calculate trip mileage from starting and ending odometer readings.', keywords: ['mileage calculator','trip mileage calculator','odometer distance'], icon: '🛣️' },
  { slug: 'density', name: 'Density Calculator', shortName: 'Density', category: 'math', description: 'Calculate density from mass and volume with explicit gram and cubic-centimeter units.', keywords: ['density calculator','mass volume density','density formula'], icon: '◈' },
  { slug: 'mass', name: 'Mass Calculator', shortName: 'Mass', category: 'math', description: 'Convert kilograms to grams and pounds with labeled mass units.', keywords: ['mass calculator','kg to pounds','mass conversion calculator'], icon: '⚖️' },
  { slug: 'weight', name: 'Weight Calculator', shortName: 'Weight', category: 'math', description: 'Convert mass in kilograms to gravitational force in newtons using standard gravity.', keywords: ['weight calculator','mass to force','newton weight calculator'], icon: '⬇️' },
  { slug: 'speed', name: 'Speed Calculator', shortName: 'Speed', category: 'math', description: 'Calculate average speed from distance in miles and elapsed time in hours.', keywords: ['speed calculator','average speed calculator','distance time speed'], icon: '🚀' },
  { slug: 'molarity', name: 'Molarity Calculator', shortName: 'Molarity', category: 'math', description: 'Calculate solution molarity from moles of solute and final volume in liters.', keywords: ['molarity calculator','molar concentration calculator','moles per liter'], icon: '⚗️' },
  { slug: 'molecular-weight', name: 'Molecular Weight Calculator', shortName: 'Molecular Weight', category: 'math', description: 'Estimate molar mass for supported simple chemical formulas.', keywords: ['molecular weight calculator','molar mass calculator','chemical formula mass'], icon: '🧬' },
  { slug: 'roman-numeral-converter', name: 'Roman Numeral Converter', shortName: 'Roman Numeral', category: 'math', description: 'Convert supported integers to Roman numerals and decode Roman symbols.', keywords: ['roman numeral converter','number to roman numerals','roman numeral calculator'], icon: 'Ⅻ' },
  { slug: 'golf-handicap', name: 'Golf Handicap Calculator', shortName: 'Golf Handicap', category: 'lifestyle', description: 'Calculate a one-round handicap differential from gross score, course rating, and slope rating.', keywords: ['golf handicap calculator','handicap differential calculator','golf score handicap'], icon: '⛳' },
  { slug: 'tire-size', name: 'Tire Size Calculator', shortName: 'Tire Size', category: 'lifestyle', description: 'Calculate nominal tire sidewall, diameter, circumference, and revolutions per mile.', keywords: ['tire size calculator','tire diameter calculator','tire comparison calculator'], icon: '◉' },
  { slug: 'discounted-cash-flow-dcf', name: 'Discounted Cash Flow Calculator', shortName: 'DCF', category: 'financial', description: 'Estimate enterprise value by discounting forecast free cash flow and a terminal value.', keywords: ['discounted cash flow calculator','DCF valuation calculator','enterprise value calculator','free cash flow valuation'], icon: '📊' },
  { slug: 'break-even', name: 'Break-even Calculator', shortName: 'Break-even', category: 'financial', description: 'Find the sales volume and revenue needed to cover fixed and variable costs.', keywords: ['break even calculator','break even point calculator','contribution margin calculator','business break even'], icon: '⚖️' },
  { slug: 'capital-gains', name: 'Capital Gains Calculator', shortName: 'Capital Gains', category: 'financial', description: 'Estimate a realized gain or loss, adjusted basis, and illustrative tax amount.', keywords: ['capital gains calculator','investment gain calculator','capital gains tax estimate','adjusted cost basis'], icon: '📈' },
  { slug: 'dividend', name: 'Dividend Calculator', shortName: 'Dividend', category: 'financial', description: 'Estimate dividend income, portfolio yield, and monthly or quarterly equivalents.', keywords: ['dividend calculator','dividend income calculator','dividend yield calculator','stock income calculator'], icon: '💰' },
  { slug: 'business-valuation', name: 'Business Valuation Calculator', shortName: 'Business Value', category: 'financial', description: 'Estimate enterprise value and equity value from revenue, EBITDA margin, valuation multiple, and net debt.', keywords: ['business valuation calculator','EBITDA multiple calculator','enterprise value calculator','company valuation estimate'], icon: '🏢' },
  { slug: 'debt-service-coverage-ratio-dscr', name: 'Debt Service Coverage Ratio Calculator', shortName: 'DSCR', category: 'financial', description: 'Calculate debt service coverage from net operating income and annual debt service.', keywords: ['DSCR calculator','debt service coverage ratio','property DSCR calculator','NOI debt service'], icon: '📐' },
  { slug: 'car-affordability', name: 'Car Affordability Calculator', shortName: 'Car Affordability', category: 'financial', description: 'Estimate a vehicle price and payment budget from income, existing debt, down payment, rate, and term assumptions.', keywords: ['car affordability calculator','how much car can I afford','auto payment budget','vehicle affordability'], icon: '🚗' },
  { slug: 'bond-yield', name: 'Bond Yield Calculator', shortName: 'Bond Yield', category: 'financial', description: 'Estimate annual coupon income, current yield, and an approximate yield to maturity.', keywords: ['bond yield calculator','current bond yield','approximate YTM calculator','coupon yield'], icon: '📜' },
];

export const CALCULATOR_BY_SLUG = Object.fromEntries(CALCULATORS.map((c) => [c.slug, c]));

export const CATEGORY_LABELS: Record<string, string> = {
  financial: 'Financial',
  fitness: 'Fitness & Health',
  math: 'Math',
  lifestyle: 'Lifestyle',
};

export const CATEGORY_COLORS: Record<string, { text: string; bg: string; border: string }> = {
  financial: { text: 'text-blue-700 dark:text-blue-400', bg: 'bg-blue-50 dark:bg-blue-950/40', border: 'border-blue-200 dark:border-blue-900/40' },
  fitness: { text: 'text-green-700 dark:text-green-400', bg: 'bg-green-50 dark:bg-green-950/40', border: 'border-green-200 dark:border-green-900/40' },
  math: { text: 'text-orange-700 dark:text-orange-400', bg: 'bg-orange-50 dark:bg-orange-950/40', border: 'border-orange-200 dark:border-orange-900/40' },
  lifestyle: { text: 'text-purple-700 dark:text-purple-400', bg: 'bg-purple-50 dark:bg-purple-950/40', border: 'border-purple-200 dark:border-purple-900/40' },
};
