import type { CalculatorSpec } from './calculator-batch-01';

export const CALCULATOR_BATCH_04: CalculatorSpec[] = [
  { slug:'square', name:'Square Calculator', category:'math', inputs:['side'], outputs:['area','perimeter'], formula:'area=s²; perimeter=4s' },
  { slug:'cube', name:'Cube Calculator', category:'math', inputs:['side'], outputs:['volume','surfaceArea'], formula:'V=s³; SA=6s²' },
  { slug:'rectangle-perimeter', name:'Rectangle Perimeter Calculator', category:'math', inputs:['length','width'], outputs:['perimeter'], formula:'2(l+w)' },
  { slug:'triangle-perimeter', name:'Triangle Perimeter Calculator', category:'math', inputs:['a','b','c'], outputs:['perimeter'], formula:'a+b+c' },
  { slug:'circle-area', name:'Circle Area Calculator', category:'math', inputs:['radius'], outputs:['area'], formula:'πr²' },
  { slug:'circle-diameter', name:'Circle Diameter Calculator', category:'math', inputs:['radius'], outputs:['diameter'], formula:'d=2r' },
  { slug:'arc-length', name:'Arc Length Calculator', category:'math', inputs:['radius','angle'], outputs:['arcLength'], formula:'s=rθ (radians)' },
  { slug:'sector-area', name:'Sector Area Calculator', category:'math', inputs:['radius','angle'], outputs:['area'], formula:'A=½r²θ (radians)' },
  { slug:'herons-formula', name:"Heron's Formula Calculator", category:'math', inputs:['a','b','c'], outputs:['area'], formula:'A=√(s(s-a)(s-b)(s-c)); s=(a+b+c)/2' },
  { slug:'distance-between-points', name:'Distance Between Points Calculator', category:'math', inputs:['x1','y1','x2','y2'], outputs:['distance'], formula:'√((x2-x1)²+(y2-y1)²)' },
  { slug:'midpoint', name:'Midpoint Calculator', category:'math', inputs:['x1','y1','x2','y2'], outputs:['x','y'], formula:'((x1+x2)/2,(y1+y2)/2)' },
  { slug:'compound-growth', name:'Compound Growth Calculator', category:'finance', inputs:['initial','growthRate','periods'], outputs:['final'], formula:'initial×(1+growthRate)^periods' },
  { slug:'savings', name:'Savings Calculator', category:'finance', inputs:['initial','contribution','rate','periods'], outputs:['futureValue'], formula:'FV=initial(1+r)^n+contribution×((1+r)^n-1)/r' },
  { slug:'mortgage', name:'Mortgage Calculator', category:'finance', inputs:['principal','annualRate','years'], outputs:['monthlyPayment'], formula:'standard fixed-rate amortization' },
  { slug:'apr', name:'APR Calculator', category:'finance', inputs:['fees','principal','rate','term'], outputs:['apr'], formula:'annualized borrowing cost' },
  { slug:'hourly-to-salary', name:'Hourly to Salary Calculator', category:'finance', inputs:['hourlyRate','hoursPerWeek','weeksPerYear'], outputs:['annualSalary'], formula:'rate×hours×weeks' },
  { slug:'salary-to-hourly', name:'Salary to Hourly Calculator', category:'finance', inputs:['annualSalary','hoursPerWeek','weeksPerYear'], outputs:['hourlyRate'], formula:'salary/(hours×weeks)' },
  { slug:'sales-profit', name:'Sales Profit Calculator', category:'finance', inputs:['revenue','expenses'], outputs:['profit','margin'], formula:'profit=revenue-expenses; margin=profit/revenue×100' },
  { slug:'currency-profit', name:'Currency Exchange Profit Calculator', category:'finance', inputs:['amount','buyRate','sellRate'], outputs:['profit'], formula:'amount×(sellRate-buyRate)' },
  { slug:'fuel-cost', name:'Fuel Cost Calculator', category:'finance', inputs:['distance','efficiency','fuelPrice'], outputs:['fuelUsed','cost'], formula:'fuelUsed=distance/efficiency; cost=fuelUsed×fuelPrice' },
  { slug:'real-estate-commission', name:'Real Estate Commission Calculator', category:'finance', inputs:['salePrice','commissionRate'], outputs:['commission'], formula:'salePrice×rate/100' },
  { slug:'bmi-category', name:'BMI Category Calculator', category:'health', inputs:['bmi'], outputs:['category'], formula:'adult BMI category thresholds' },
  { slug:'lean-body-mass', name:'Lean Body Mass Calculator', category:'health', inputs:['weight','height','sex'], outputs:['leanMass'], formula:'sex-specific LBM estimate' },
  { slug:'macro-calculator', name:'Macro Calculator', category:'health', inputs:['calories','proteinPercent','carbPercent','fatPercent'], outputs:['proteinGrams','carbGrams','fatGrams'], formula:'grams=(calories×percent)/calorieDensity' },
  { slug:'tdee', name:'TDEE Calculator', category:'health', inputs:['bmr','activityFactor'], outputs:['tdee'], formula:'TDEE=BMR×activityFactor' },
  { slug:'ideal-body-weight', name:'Ideal Body Weight Calculator', category:'health', inputs:['height','sex'], outputs:['idealWeight'], formula:'height-based clinical estimate' },
  { slug:'pregnancy-due-date', name:'Pregnancy Due Date Calculator', category:'health', inputs:['lastMenstrualPeriod'], outputs:['dueDate'], formula:'LMP + 280 days' },
  { slug:'ovulation', name:'Ovulation Calculator', category:'health', inputs:['cycleLength','periodStart'], outputs:['estimatedOvulation'], formula:'cycle-based estimate' },
  { slug:'heart-rate-zone', name:'Heart Rate Zone Calculator', category:'health', inputs:['age','restingHeartRate'], outputs:['zones'], formula:'heart-rate reserve method' },
  { slug:'basal-calorie', name:'Basal Calorie Calculator', category:'health', inputs:['weight','height','age','sex'], outputs:['calories'], formula:'BMR estimation' },
  { slug:'running-calorie', name:'Running Calorie Calculator', category:'sports', inputs:['weight','distance','pace'], outputs:['calories'], formula:'exercise energy estimate' },
  { slug:'one-rep-max', name:'One Rep Max Calculator', category:'sports', inputs:['weight','reps'], outputs:['oneRepMax'], formula:'Epley: weight×(1+reps/30)' },
  { slug:'vo2-max', name:'VO2 Max Calculator', category:'sports', inputs:['distance','time'], outputs:['vo2max'], formula:'running-test estimation' },
  { slug:'calorie-burn', name:'Calorie Burn Calculator', category:'sports', inputs:['weight','duration','met'], outputs:['calories'], formula:'MET×3.5×kg/200×minutes' },
  { slug:'cycling-speed', name:'Cycling Speed Calculator', category:'sports', inputs:['distance','time'], outputs:['speed'], formula:'distance/time' },
  { slug:'baseball-batting-average', name:'Batting Average Calculator', category:'sports', inputs:['hits','atBats'], outputs:['average'], formula:'hits/atBats' },
  { slug:'density-conversion', name:'Density Conversion Calculator', category:'conversion', inputs:['value','fromUnit','toUnit'], outputs:['converted'], formula:'unit conversion through SI base' },
  { slug:'length-conversion', name:'Length Conversion Calculator', category:'conversion', inputs:['value','fromUnit','toUnit'], outputs:['converted'], formula:'unit conversion through meter' },
  { slug:'area-conversion', name:'Area Conversion Calculator', category:'conversion', inputs:['value','fromUnit','toUnit'], outputs:['converted'], formula:'unit conversion through square meter' },
  { slug:'volume-conversion', name:'Volume Conversion Calculator', category:'conversion', inputs:['value','fromUnit','toUnit'], outputs:['converted'], formula:'unit conversion through cubic meter' },
  { slug:'weight-conversion', name:'Weight Conversion Calculator', category:'conversion', inputs:['value','fromUnit','toUnit'], outputs:['converted'], formula:'unit conversion through kilogram' },
  { slug:'pressure-conversion', name:'Pressure Conversion Calculator', category:'conversion', inputs:['value','fromUnit','toUnit'], outputs:['converted'], formula:'unit conversion through pascal' },
  { slug:'energy-conversion', name:'Energy Conversion Calculator', category:'conversion', inputs:['value','fromUnit','toUnit'], outputs:['converted'], formula:'unit conversion through joule' },
  { slug:'power-conversion', name:'Power Conversion Calculator', category:'conversion', inputs:['value','fromUnit','toUnit'], outputs:['converted'], formula:'unit conversion through watt' },
  { slug:'temperature-conversion', name:'Temperature Conversion Calculator', category:'conversion', inputs:['value','fromUnit','toUnit'], outputs:['converted'], formula:'temperature scale transformation' },
  { slug:'speed-conversion', name:'Speed Conversion Calculator', category:'conversion', inputs:['value','fromUnit','toUnit'], outputs:['converted'], formula:'unit conversion through m/s' },
  { slug:'molarity-dilution', name:'Molarity Dilution Calculator', category:'chemistry', inputs:['initialMolarity','initialVolume','finalMolarity'], outputs:['finalVolume'], formula:'M1V1=M2V2' },
  { slug:'percent-composition', name:'Percent Composition Calculator', category:'chemistry', inputs:['elementMass','compoundMass'], outputs:['percent'], formula:'elementMass/compoundMass×100' },
  { slug:'empirical-formula', name:'Empirical Formula Calculator', category:'chemistry', inputs:['elementMasses'], outputs:['formula'], formula:'convert masses to mole ratios and reduce' },
  { slug:'confidence-interval', name:'Confidence Interval Calculator', category:'statistics', inputs:['mean','standardDeviation','sampleSize','confidenceLevel'], outputs:['interval'], formula:'mean ± criticalValue×standardError' },
  { slug:'percentile', name:'Percentile Calculator', category:'statistics', inputs:['values','percentile'], outputs:['value'], formula:'ordered-data percentile' },
  { slug:'quartile', name:'Quartile Calculator', category:'statistics', inputs:['values'], outputs:['q1','q2','q3'], formula:'ordered-data quartiles' },
  { slug:'z-test', name:'Z Test Calculator', category:'statistics', inputs:['sampleMean','populationMean','standardDeviation','sampleSize'], outputs:['z'], formula:'(sampleMean-populationMean)/(sd/√n)' },
];
