import type { CalculatorSpec } from './calculator-batch-01';

export const CALCULATOR_BATCH_02: CalculatorSpec[] = [
  { slug: 'ratio', name: 'Ratio Calculator', category: 'math', inputs: ['a','b'], outputs:['ratio'], formula:'a:b' },
  { slug: 'proportion', name: 'Proportion Calculator', category:'math', inputs:['a','b','c'], outputs:['d'], formula:'a/b = c/d; d = b*c/a', reverseSolving:['a = b*c/d','b = a*d/c','c = a*d/b'] },
  { slug: 'fraction', name:'Fraction Calculator', category:'math', inputs:['numerator1','denominator1','operator','numerator2','denominator2'], outputs:['result'], formula:'exact rational arithmetic' },
  { slug:'gcd', name:'GCD Calculator', category:'math', inputs:['values'], outputs:['gcd'], formula:'greatest common divisor' },
  { slug:'lcm', name:'LCM Calculator', category:'math', inputs:['values'], outputs:['lcm'], formula:'least common multiple' },
  { slug:'factorial', name:'Factorial Calculator', category:'math', inputs:['n'], outputs:['factorial'], formula:'n! = n × (n-1) × ... × 1' },
  { slug:'permutation', name:'Permutation Calculator', category:'math', inputs:['n','r'], outputs:['permutations'], formula:'nPr = n!/(n-r)!' },
  { slug:'combination', name:'Combination Calculator', category:'math', inputs:['n','r'], outputs:['combinations'], formula:'nCr = n!/(r!(n-r)!)' },
  { slug:'quadratic-equation', name:'Quadratic Equation Calculator', category:'math', inputs:['a','b','c'], outputs:['roots'], formula:'x = (-b ± √(b²-4ac))/(2a)' },
  { slug:'absolute-value', name:'Absolute Value Calculator', category:'math', inputs:['x'], outputs:['absolute'], formula:'|x|' },
  { slug:'fraction-to-decimal', name:'Fraction to Decimal Calculator', category:'math', inputs:['numerator','denominator'], outputs:['decimal'], formula:'numerator/denominator' },
  { slug:'decimal-to-fraction', name:'Decimal to Fraction Calculator', category:'math', inputs:['decimal'], outputs:['fraction'], formula:'convert decimal to reduced rational form' },
  { slug:'break-even', name:'Break Even Calculator', category:'finance', inputs:['fixedCosts','pricePerUnit','variableCostPerUnit'], outputs:['breakEvenUnits','breakEvenRevenue'], formula:'units = fixedCosts/(pricePerUnit-variableCostPerUnit)' },
  { slug:'roi', name:'ROI Calculator', category:'finance', inputs:['gain','cost'], outputs:['roiPercent'], formula:'(gain-cost)/cost × 100' },
  { slug:'commission', name:'Commission Calculator', category:'finance', inputs:['sales','commissionRate'], outputs:['commission'], formula:'sales × commissionRate / 100' },
  { slug:'tip', name:'Tip Calculator', category:'finance', inputs:['bill','tipPercent','people'], outputs:['tip','total','perPerson'], formula:'tip=bill×rate/100; total=bill+tip' },
  { slug:'loan-payment', name:'Loan Payment Calculator', category:'finance', inputs:['principal','rate','periods'], outputs:['payment'], formula:'P×r×(1+r)^n/((1+r)^n-1)' },
  { slug:'future-value', name:'Future Value Calculator', category:'finance', inputs:['presentValue','rate','periods'], outputs:['futureValue'], formula:'PV×(1+r)^n' },
  { slug:'present-value', name:'Present Value Calculator', category:'finance', inputs:['futureValue','rate','periods'], outputs:['presentValue'], formula:'FV/(1+r)^n' },
  { slug:'debt-to-income', name:'Debt to Income Calculator', category:'finance', inputs:['monthlyDebt','grossMonthlyIncome'], outputs:['dtiPercent'], formula:'monthlyDebt/grossMonthlyIncome × 100' },
  { slug:'inflation', name:'Inflation Calculator', category:'finance', inputs:['amount','inflationRate','years'], outputs:['futureAmount'], formula:'amount×(1+rate)^years' },
  { slug:'age', name:'Age Calculator', category:'everyday-life', inputs:['birthDate','targetDate'], outputs:['ageYears','ageMonths','ageDays'], formula:'calendar date difference' },
  { slug:'time-difference', name:'Time Difference Calculator', category:'everyday-life', inputs:['start','end'], outputs:['duration'], formula:'end-start' },
  { slug:'date-difference', name:'Date Difference Calculator', category:'everyday-life', inputs:['startDate','endDate'], outputs:['days'], formula:'calendar day difference' },
  { slug:'hours-to-minutes', name:'Hours to Minutes Calculator', category:'conversion', inputs:['hours'], outputs:['minutes'], formula:'hours×60' },
  { slug:'minutes-to-seconds', name:'Minutes to Seconds Calculator', category:'conversion', inputs:['minutes'], outputs:['seconds'], formula:'minutes×60' },
  { slug:'kilometers-to-miles', name:'Kilometers to Miles Calculator', category:'conversion', inputs:['kilometers'], outputs:['miles'], formula:'kilometers×0.621371192237' },
  { slug:'miles-to-kilometers', name:'Miles to Kilometers Calculator', category:'conversion', inputs:['miles'], outputs:['kilometers'], formula:'miles×1.609344' },
  { slug:'celsius-to-fahrenheit', name:'Celsius to Fahrenheit Calculator', category:'conversion', inputs:['celsius'], outputs:['fahrenheit'], formula:'celsius×9/5+32' },
  { slug:'fahrenheit-to-celsius', name:'Fahrenheit to Celsius Calculator', category:'conversion', inputs:['fahrenheit'], outputs:['celsius'], formula:'(fahrenheit-32)×5/9' },
  { slug:'meters-to-feet', name:'Meters to Feet Calculator', category:'conversion', inputs:['meters'], outputs:['feet'], formula:'meters×3.280839895' },
  { slug:'feet-to-meters', name:'Feet to Meters Calculator', category:'conversion', inputs:['feet'], outputs:['meters'], formula:'feet×0.3048' },
  { slug:'kinetic-energy', name:'Kinetic Energy Calculator', category:'physics', inputs:['mass','velocity'], outputs:['energy'], formula:'E=½mv²' },
  { slug:'potential-energy', name:'Potential Energy Calculator', category:'physics', inputs:['mass','gravity','height'], outputs:['energy'], formula:'E=mgh' },
  { slug:'work', name:'Work Calculator', category:'physics', inputs:['force','distance','angle'], outputs:['work'], formula:'W=F×d×cos(angle)' },
  { slug:'power', name:'Power Calculator', category:'physics', inputs:['work','time'], outputs:['power'], formula:'P=W/t' },
  { slug:'pressure', name:'Pressure Calculator', category:'physics', inputs:['force','area'], outputs:['pressure'], formula:'P=F/A' },
  { slug:'ohms-law', name:"Ohm's Law Calculator", category:'physics', inputs:['voltage','current','resistance'], outputs:['missingVariable'], formula:'V=I×R' },
  { slug:'bmi-prime', name:'BMI Prime Calculator', category:'health', inputs:['bmi'], outputs:['bmiPrime'], formula:'bmi/25' },
  { slug:'body-fat', name:'Body Fat Calculator', category:'health', inputs:['sex','waist','neck','height','hip'], outputs:['bodyFatPercent'], formula:'US Navy body-fat estimation' },
  { slug:'ideal-weight', name:'Ideal Weight Calculator', category:'health', inputs:['height','sex'], outputs:['weightRange'], formula:'height-based healthy-weight estimate' },
  { slug:'protein', name:'Protein Intake Calculator', category:'health', inputs:['weight','activityLevel','goal'], outputs:['dailyProtein'], formula:'weight × goal/activity factor' },
  { slug:'water-intake', name:'Water Intake Calculator', category:'health', inputs:['weight','activity','climate'], outputs:['dailyWater'], formula:'weight/activity based estimate' },
  { slug:'standard-deviation', name:'Standard Deviation Calculator', category:'statistics', inputs:['values'], outputs:['standardDeviation'], formula:'population or sample standard deviation' },
  { slug:'variance', name:'Variance Calculator', category:'statistics', inputs:['values'], outputs:['variance'], formula:'mean squared deviation' },
  { slug:'median', name:'Median Calculator', category:'statistics', inputs:['values'], outputs:['median'], formula:'middle ordered value' },
  { slug:'mode', name:'Mode Calculator', category:'statistics', inputs:['values'], outputs:['mode'], formula:'most frequent value(s)' },
  { slug:'mean', name:'Mean Calculator', category:'statistics', inputs:['values'], outputs:['mean'], formula:'sum(values)/count(values)' },
  { slug:'rectangle-area', name:'Rectangle Area Calculator', category:'construction', inputs:['length','width'], outputs:['area'], formula:'length×width' },
  { slug:'triangle-area', name:'Triangle Area Calculator', category:'construction', inputs:['base','height'], outputs:['area'], formula:'½×base×height' },
  { slug:'cylinder-volume', name:'Cylinder Volume Calculator', category:'construction', inputs:['radius','height'], outputs:['volume'], formula:'πr²h' },
  { slug:'sphere-volume', name:'Sphere Volume Calculator', category:'construction', inputs:['radius'], outputs:['volume'], formula:'4πr³/3' },
  { slug:'molar-mass', name:'Molar Mass Calculator', category:'chemistry', inputs:['formula'], outputs:['molarMass'], formula:'sum(element atomic masses × subscripts)' },
  { slug:'ph', name:'pH Calculator', category:'chemistry', inputs:['hydrogenIonConcentration'], outputs:['pH'], formula:'pH=-log10[H+]' },
  { slug:'mass-moles', name:'Mass to Moles Calculator', category:'chemistry', inputs:['mass','molarMass'], outputs:['moles'], formula:'moles=mass/molarMass' },
  { slug:'moles-mass', name:'Moles to Mass Calculator', category:'chemistry', inputs:['moles','molarMass'], outputs:['mass'], formula:'mass=moles×molarMass' },
  { slug:'calorie-deficit', name:'Calorie Deficit Calculator', category:'health', inputs:['maintenanceCalories','targetCalories'], outputs:['deficit'], formula:'maintenance-target' },
];
