import type { CalculatorSpec } from './calculator-batch-01';
export const CALCULATOR_BATCH_03: CalculatorSpec[] = [
{slug:'cube-root',name:'Cube Root Calculator',category:'math',inputs:['value'],outputs:['root'],formula:'∛value'},
{slug:'power-mod',name:'Power Mod Calculator',category:'math',inputs:['base','exponent','modulus'],outputs:['remainder'],formula:'base^exponent mod modulus'},
{slug:'modulo',name:'Modulo Calculator',category:'math',inputs:['dividend','divisor'],outputs:['remainder'],formula:'dividend mod divisor'},
{slug:'prime-factorization',name:'Prime Factorization Calculator',category:'math',inputs:['integer'],outputs:['factors'],formula:'factor integer into primes'},
{slug:'prime-number',name:'Prime Number Calculator',category:'math',inputs:['integer'],outputs:['isPrime'],formula:'integer has exactly two positive divisors'},
{slug:'rounding',name:'Rounding Calculator',category:'math',inputs:['value','decimalPlaces'],outputs:['rounded'],formula:'round(value,n)'},
{slug:'weighted-average',name:'Weighted Average Calculator',category:'math',inputs:['values','weights'],outputs:['average'],formula:'sum(value×weight)/sum(weights)'},
{slug:'geometric-mean',name:'Geometric Mean Calculator',category:'math',inputs:['values'],outputs:['mean'],formula:'(product(values))^(1/n)'},
{slug:'harmonic-mean',name:'Harmonic Mean Calculator',category:'math',inputs:['values'],outputs:['mean'],formula:'n/sum(1/value)'},
{slug:'root',name:'Root Calculator',category:'math',inputs:['value','index'],outputs:['root'],formula:'value^(1/index)'},
{slug:'scientific-notation-operations',name:'Scientific Notation Operations Calculator',category:'math',inputs:['a','b','operation'],outputs:['result'],formula:'operation on normalized scientific notation'},
{slug:'significant-figures',name:'Significant Figures Calculator',category:'math',inputs:['value','figures'],outputs:['rounded'],formula:'round to significant figures'},
{slug:'absolute-change',name:'Absolute Change Calculator',category:'math',inputs:['oldValue','newValue'],outputs:['change'],formula:'newValue-oldValue'},
{slug:'unit-rate',name:'Unit Rate Calculator',category:'math',inputs:['quantity','units'],outputs:['rate'],formula:'quantity/units'},
{slug:'cross-multiplication',name:'Cross Multiplication Calculator',category:'math',inputs:['a','b','c'],outputs:['d'],formula:'a/b=c/d'},
{slug:'salary-to-hourly',name:'Salary to Hourly Calculator',category:'finance',inputs:['salary','hoursPerWeek','weeksPerYear'],outputs:['hourlyRate'],formula:'salary/(hoursPerWeek×weeksPerYear)'},
{slug:'hourly-to-salary',name:'Hourly to Salary Calculator',category:'finance',inputs:['hourlyRate','hoursPerWeek','weeksPerYear'],outputs:['salary'],formula:'hourlyRate×hoursPerWeek×weeksPerYear'},
{slug:'mortgage-payment',name:'Mortgage Payment Calculator',category:'finance',inputs:['principal','annualRate','termYears'],outputs:['payment'],formula:'monthly amortizing payment'},
{slug:'amortization',name:'Amortization Calculator',category:'finance',inputs:['principal','rate','term'],outputs:['payment','schedule'],formula:'amortization schedule'},
{slug:'savings',name:'Savings Calculator',category:'finance',inputs:['initial','contribution','rate','periods'],outputs:['futureValue'],formula:'compound growth plus periodic contributions'},
{slug:'cagr',name:'CAGR Calculator',category:'finance',inputs:['beginning','ending','years'],outputs:['cagr'],formula:'(ending/beginning)^(1/years)-1'},
{slug:'payback-period',name:'Payback Period Calculator',category:'finance',inputs:['initialInvestment','cashFlows'],outputs:['period'],formula:'first period cumulative cash flow reaches investment'},
{slug:'gross-profit',name:'Gross Profit Calculator',category:'finance',inputs:['revenue','costOfGoods'],outputs:['grossProfit','margin'],formula:'revenue-costOfGoods'},
{slug:'net-profit-margin',name:'Net Profit Margin Calculator',category:'finance',inputs:['netProfit','revenue'],outputs:['margin'],formula:'netProfit/revenue×100'},
{slug:'price-per-unit',name:'Price Per Unit Calculator',category:'finance',inputs:['totalPrice','quantity'],outputs:['unitPrice'],formula:'totalPrice/quantity'},
{slug:'mortgage-affordability',name:'Mortgage Affordability Calculator',category:'finance',inputs:['income','debts','rate','term'],outputs:['affordableLoan'],formula:'debt-to-income constrained loan estimate'},
{slug:'fuel-cost',name:'Fuel Cost Calculator',category:'everyday-life',inputs:['distance','efficiency','fuelPrice'],outputs:['cost'],formula:'distance/efficiency×fuelPrice'},
{slug:'gas-mileage',name:'Gas Mileage Calculator',category:'everyday-life',inputs:['distance','fuelUsed'],outputs:['efficiency'],formula:'distance/fuelUsed'},
{slug:'time-to-decimal',name:'Time to Decimal Calculator',category:'everyday-life',inputs:['hours','minutes','seconds'],outputs:['decimalHours'],formula:'hours+minutes/60+seconds/3600'},
{slug:'business-days',name:'Business Days Calculator',category:'everyday-life',inputs:['startDate','endDate','holidays'],outputs:['businessDays'],formula:'count weekdays excluding holidays'},
{slug:'day-of-year',name:'Day of the Year Calculator',category:'everyday-life',inputs:['date'],outputs:['dayNumber'],formula:'ordinal day within year'},
{slug:'leap-year',name:'Leap Year Calculator',category:'everyday-life',inputs:['year'],outputs:['isLeap'],formula:'divisible by 4 except centuries unless divisible by 400'},
{slug:'countdown',name:'Countdown Calculator',category:'everyday-life',inputs:['targetDateTime','now'],outputs:['duration'],formula:'target-now'},
{slug:'percentage-of-time',name:'Percentage of Time Calculator',category:'everyday-life',inputs:['elapsed','total'],outputs:['percent'],formula:'elapsed/total×100'},
{slug:'miles-per-hour-to-kmh',name:'MPH to KMH Calculator',category:'conversion',inputs:['mph'],outputs:['kmh'],formula:'mph×1.609344'},
{slug:'kmh-to-mph',name:'KMH to MPH Calculator',category:'conversion',inputs:['kmh'],outputs:['mph'],formula:'kmh/1.609344'},
{slug:'pounds-to-kilograms',name:'Pounds to Kilograms Calculator',category:'conversion',inputs:['pounds'],outputs:['kilograms'],formula:'pounds×0.45359237'},
{slug:'kilograms-to-pounds',name:'Kilograms to Pounds Calculator',category:'conversion',inputs:['kilograms'],outputs:['pounds'],formula:'kilograms/0.45359237'},
{slug:'liters-to-gallons',name:'Liters to Gallons Calculator',category:'conversion',inputs:['liters'],outputs:['gallons'],formula:'liters×0.2641720524'},
{slug:'gallons-to-liters',name:'Gallons to Liters Calculator',category:'conversion',inputs:['gallons'],outputs:['liters'],formula:'gallons×3.785411784'},
{slug:'square-meters-to-square-feet',name:'Square Meters to Square Feet Calculator',category:'conversion',inputs:['squareMeters'],outputs:['squareFeet'],formula:'squareMeters×10.7639104167'},
{slug:'square-feet-to-square-meters',name:'Square Feet to Square Meters Calculator',category:'conversion',inputs:['squareFeet'],outputs:['squareMeters'],formula:'squareFeet×0.09290304'},
{slug:'newtons-to-pounds-force',name:'Newtons to Pounds Force Calculator',category:'conversion',inputs:['newtons'],outputs:['poundsForce'],formula:'newtons×0.224808943'},
{slug:'watts-to-horsepower',name:'Watts to Horsepower Calculator',category:'conversion',inputs:['watts'],outputs:['horsepower'],formula:'watts/745.699872'},
{slug:'momentum',name:'Momentum Calculator',category:'physics',inputs:['mass','velocity'],outputs:['momentum'],formula:'p=mv'},
{slug:'impulse',name:'Impulse Calculator',category:'physics',inputs:['force','time'],outputs:['impulse'],formula:'J=FΔt'},
{slug:'frequency',name:'Frequency Calculator',category:'physics',inputs:['cycles','time'],outputs:['frequency'],formula:'f=cycles/time'},
{slug:'wavelength',name:'Wavelength Calculator',category:'physics',inputs:['waveSpeed','frequency'],outputs:['wavelength'],formula:'λ=v/f'},
{slug:'period',name:'Period Calculator',category:'physics',inputs:['frequency'],outputs:['period'],formula:'T=1/f'},
{slug:'angular-velocity',name:'Angular Velocity Calculator',category:'physics',inputs:['angle','time'],outputs:['angularVelocity'],formula:'ω=Δθ/Δt'},
{slug:'torque',name:'Torque Calculator',category:'physics',inputs:['force','leverArm','angle'],outputs:['torque'],formula:'τ=rFsin(angle)'},
{slug:'gravitational-force',name:'Gravitational Force Calculator',category:'physics',inputs:['m1','m2','distance'],outputs:['force'],formula:'F=Gm1m2/r²'},
{slug:'specific-heat',name:'Specific Heat Calculator',category:'physics',inputs:['heat','mass','temperatureChange'],outputs:['specificHeat'],formula:'c=Q/(mΔT)'},
{slug:'heat-transfer',name:'Heat Transfer Calculator',category:'physics',inputs:['mass','specificHeat','temperatureChange'],outputs:['heat'],formula:'Q=mcΔT'},
{slug:'molarity-dilution',name:'Molarity Dilution Calculator',category:'chemistry',inputs:['m1','v1','m2'],outputs:['v2'],formula:'M1V1=M2V2'},
{slug:'mole-fraction',name:'Mole Fraction Calculator',category:'chemistry',inputs:['componentMoles','totalMoles'],outputs:['fraction'],formula:'component/total'},
{slug:'percent-yield',name:'Percent Yield Calculator',category:'chemistry',inputs:['actualYield','theoreticalYield'],outputs:['percentYield'],formula:'actual/theoretical×100'},
{slug:'half-life',name:'Half Life Calculator',category:'chemistry',inputs:['initial','remaining','halfLife'],outputs:['time'],formula:'N=N0(1/2)^(t/tHalf)'},
{slug:'molarity-from-mass',name:'Molarity from Mass Calculator',category:'chemistry',inputs:['mass','molarMass','volume'],outputs:['molarity'],formula:'mass/(molarMass×volume)'},
{slug:'one-rep-max',name:'One Rep Max Calculator',category:'sports',inputs:['weight','reps'],outputs:['oneRepMax'],formula:'estimate 1RM from load and repetitions'},
{slug:'running-pace',name:'Running Pace Calculator',category:'sports',inputs:['distance','time'],outputs:['pace'],formula:'time/distance'},
{slug:'running-speed',name:'Running Speed Calculator',category:'sports',inputs:['distance','time'],outputs:['speed'],formula:'distance/time'},
{slug:'cycling-speed',name:'Cycling Speed Calculator',category:'sports',inputs:['distance','time'],outputs:['speed'],formula:'distance/time'},
{slug:'calories-burned-running',name:'Calories Burned Running Calculator',category:'sports',inputs:['weight','distance','intensity'],outputs:['calories'],formula:'activity-based energy expenditure estimate'},
{slug:'confidence-interval',name:'Confidence Interval Calculator',category:'statistics',inputs:['sampleMean','standardDeviation','sampleSize','confidenceLevel'],outputs:['lower','upper'],formula:'mean ± criticalValue×standardError'},
{slug:'p-value',name:'P-value Calculator',category:'statistics',inputs:['testStatistic','degreesOfFreedom','testType'],outputs:['pValue'],formula:'tail probability under null distribution'},
{slug:'percentile',name:'Percentile Calculator',category:'statistics',inputs:['values','target'],outputs:['percentile'],formula:'rank-based percentile'},
{slug:'quartile',name:'Quartile Calculator',category:'statistics',inputs:['values'],outputs:['q1','q2','q3'],formula:'ordered-data quartiles'},
{slug:'z-test',name:'Z Test Calculator',category:'statistics',inputs:['sampleMean','populationMean','standardError'],outputs:['z'],formula:'(sampleMean-populationMean)/SE'},
];
