import React, { useState, useEffect } from 'react';
import { Share2, Download, Award, Sparkles } from 'lucide-react';
import { Calculator } from '../types';
import { validateGeneratedCode } from '../security';

interface DynamicCalculatorWidgetProps {
  calculator: Calculator;
  onShare: () => void;
  onExportPDF: () => void;
  shareSuccess: boolean;
}

export function DynamicCalculatorWidget({
  calculator,
  onShare,
  onExportPDF,
  shareSuccess
}: DynamicCalculatorWidgetProps) {
  const { name, category, metadata } = calculator;
  const inputs = metadata.inputs || [];
  const outputs = metadata.outputs || [];
  const calculateBody = metadata.calculateBody || '';

  // Initialize inputs state with default values
  const [userInputs, setUserInputs] = useState<Record<string, number>>({});
  const [results, setResults] = useState<Record<string, any>>({});
  const [warning, setWarning] = useState<string | null>(null);

  useEffect(() => {
    const defaults: Record<string, number> = {};
    inputs.forEach((inp: any) => {
      defaults[inp.name] = inp.defaultValue !== undefined ? inp.defaultValue : 0;
    });
    setUserInputs(defaults);
    setWarning(null);
  }, [calculator]);

  // Run calculation dynamically whenever inputs change
  useEffect(() => {
    if (Object.keys(userInputs).length === 0 || !calculateBody) return;
    try {
      // Validate inputs
      let currentWarning: string | null = null;
      inputs.forEach((inp: any) => {
        const val = userInputs[inp.name] || 0;
        if (inp.min !== undefined && val < inp.min) {
          currentWarning = `${inp.label} est inférieur au minimum requis de ${inp.min}.`;
        }
        if (inp.max !== undefined && val > inp.max) {
          currentWarning = `${inp.label} dépasse le maximum autorisé de ${inp.max}.`;
        }
      });

      if (currentWarning) {
        setWarning(currentWarning);
        return;
      }

      const reviewIssues = validateGeneratedCode({ meta: { calculateBody } });
      if (reviewIssues.length > 0) {
        setWarning('This calculator code was generated by AI and is awaiting review. Please use a trusted version before relying on results.');
        return;
      }

      setWarning(null);
      const calcFn = new Function('inputs', calculateBody);
      const outputVal = calcFn(userInputs);
      setResults(outputVal || {});
    } catch (err: any) {
      setWarning('Erreur de calcul: ' + err.message);
    }
  }, [userInputs, calculateBody, inputs]);

  const handleInputChange = (name: string, value: string) => {
    const num = parseFloat(value);
    setUserInputs(prev => ({
      ...prev,
      [name]: isNaN(num) ? 0 : num
    }));
  };

  // Convert category slug to nice name
  let catBreadcrumb = 'Other';
  if (category === 'financial') catBreadcrumb = 'Financial';
  else if (category === 'fitness') catBreadcrumb = 'Fitness & Health';
  else if (category === 'math') catBreadcrumb = 'Math';
  else if (category === 'more') catBreadcrumb = 'Other';
  else catBreadcrumb = category.charAt(0).toUpperCase() + category.slice(1);

  return (
    <div id={`dynamic-calc-${calculator.id}`} className="max-w-5xl mx-auto space-y-8 select-none">
      {/* Header section */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-end gap-4 border-b border-slate-200 pb-5 text-left">
        <div>
          <div className="text-xs text-blue-600 font-bold uppercase tracking-tight mb-1">
            Home / {catBreadcrumb} /
          </div>
          <h2 className="text-3xl font-extrabold tracking-tight flex items-center gap-2">
            {name}
            <Sparkles className="w-5 h-5 text-amber-500 fill-amber-500 animate-pulse" />
          </h2>
          <p className="text-sm text-slate-500">{metadata.description}</p>
        </div>
        <div className="flex gap-2">
          <button 
            onClick={onExportPDF} 
            className="flex items-center gap-2 px-3.5 py-2 bg-white border border-slate-200 rounded-lg text-xs font-semibold hover:bg-slate-50 shadow-sm transition cursor-pointer"
          >
            <Download className="w-3.5 h-3.5" /> Export PDF
          </button>
          <button 
            onClick={onShare} 
            className={`flex items-center gap-2 px-3.5 py-2 rounded-lg text-xs font-semibold shadow-sm transition cursor-pointer ${
              shareSuccess 
                ? 'bg-green-600 text-white hover:bg-green-700' 
                : 'bg-slate-900 text-white hover:bg-slate-800'
            }`}
          >
            <Share2 className="w-3.5 h-3.5" /> {shareSuccess ? 'Copied!' : 'Share Tool'}
          </button>
        </div>
      </div>

      {/* Main Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 text-left">
        {/* Left Column: Input Fields */}
        <div className="lg:col-span-5 bg-white rounded-2xl shadow-sm border border-slate-200 p-6 space-y-5">
          <h3 className="font-bold text-slate-900 border-b border-slate-100 pb-3 uppercase tracking-wider text-xs">
            Calculator Inputs
          </h3>

          <div className="space-y-4">
            {inputs.map((inp: any) => (
              <div key={inp.name} className="space-y-1">
                <div className="flex justify-between items-center">
                  <label className="text-[10px] font-bold text-slate-500 uppercase tracking-wider">
                    {inp.label}
                  </label>
                  {inp.suffix && (
                    <span className="text-[9px] text-slate-400 font-bold font-mono uppercase bg-slate-100 px-1.5 py-0.5 rounded">
                      {inp.suffix}
                    </span>
                  )}
                </div>
                <input
                  type="number"
                  value={userInputs[inp.name] !== undefined ? userInputs[inp.name] : ''}
                  onChange={(e) => handleInputChange(inp.name, e.target.value)}
                  className="w-full p-3 bg-slate-50 border border-slate-200 rounded-xl font-semibold text-sm focus:bg-white focus:outline-none focus:ring-2 focus:ring-blue-500/10 transition"
                  placeholder={`e.g. ${inp.defaultValue || ''}`}
                />
                {inp.helpText && (
                  <span className="text-[10px] text-slate-400 mt-1 block leading-normal">
                    {inp.helpText}
                  </span>
                )}
              </div>
            ))}
          </div>

          {warning && (
            <div className="p-3 bg-amber-50 border border-amber-200 rounded-xl text-xs text-amber-700 font-semibold">
              ⚠️ {warning}
            </div>
          )}
        </div>

        {/* Right Column: Output Display Cards */}
        <div className="lg:col-span-7 flex flex-col gap-6">
          <div className="bg-slate-900 text-white rounded-2xl shadow-md border border-slate-800 p-6 flex-1 flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between border-b border-white/10 pb-4 mb-6">
                <h3 className="font-bold uppercase tracking-widest text-[10px] text-slate-400">
                  Live Results
                </h3>
                <span className="bg-blue-500/10 text-blue-400 px-2.5 py-1 rounded-full text-[9px] font-bold uppercase tracking-wider flex items-center gap-1">
                  <Award className="w-3 h-3" /> Real-Time
                </span>
              </div>

              {/* Outputs Display */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {outputs.map((out: any) => {
                  const val = results[out.name];
                  const displayValue = typeof val === 'number' 
                    ? val.toLocaleString(undefined, { minimumFractionDigits: 0, maximumFractionDigits: 2 })
                    : val !== undefined ? val : '0';

                  return (
                    <div key={out.name} className="p-4 bg-white/5 border border-white/10 rounded-xl hover:bg-white/10 transition">
                      <span className="text-[10px] font-bold text-slate-400 block truncate uppercase tracking-wider mb-1">
                        {out.label}
                      </span>
                      <span className="text-xl md:text-2xl font-black text-white font-mono block">
                        {out.suffix === '$' ? `$${displayValue}` : `${displayValue}${out.suffix || ''}`}
                      </span>
                    </div>
                  );
                })}
              </div>
            </div>

            <div className="mt-6 pt-4 border-t border-white/10 flex items-center justify-between text-[10px] text-slate-400 font-bold uppercase tracking-wider">
              <span>Client-side formulas and logic</span>
              <span className="text-[#a8c878]">Private and secure by design</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
