'use client';

import { AgeCalculator } from './AgeCalculator';
import { BMICalculator } from './BMICalculator';
import { CalorieCalculator } from './CalorieCalculator';
import { GPACalculator } from './GPACalculator';
import { LoanCalculator } from './LoanCalculator';
import { MortgageCalculator } from './MortgageCalculator';
import { MortgageAmortizationCalculator } from './MortgageAmortizationCalculator';
import { HouseAffordabilityCalculator } from './HouseAffordabilityCalculator';
import { RentCalculator } from './RentCalculator';
import { RentVsBuyCalculator } from './RentVsBuyCalculator';
import { PercentageCalculator } from './PercentageCalculator';
import { TipCalculator } from './TipCalculator';
import { RentalPropertyCalculator } from './RentalPropertyCalculator';
import { RealEstateCalculator } from './RealEstateCalculator';
import { FHALoanCalculator } from './FHALoanCalculator';
import { VAMortgageCalculator } from './VAMortgageCalculator';
import { HomeEquityLoanCalculator } from './HomeEquityLoanCalculator';
import { HelocCalculator } from './HelocCalculator';
import { DownPaymentCalculator } from './DownPaymentCalculator';
import { RefinanceCalculator } from './RefinanceCalculator';
import { MortgagePayoffCalculator } from './MortgagePayoffCalculator';
import { MortgageUkCalculator } from './MortgageUkCalculator';
import { CanadianMortgageCalculator } from './CanadianMortgageCalculator';
import { PersonalLoanCalculator } from './PersonalLoanCalculator';
import { AutoLoanCalculator } from './AutoLoanCalculator';
import { AutoLeaseCalculator } from './AutoLeaseCalculator';
import { BoatLoanCalculator } from './BoatLoanCalculator';
import { PaymentCalculator, RepaymentCalculator, StudentLoanCalculator } from './LoanProductCalculator';
import { CollegeCostCalculator } from './CollegeCostCalculator';
import { CreditCardCalculator, CreditCardsPayoffCalculator, DebtPayoffCalculator, DebtConsolidationCalculator, DtiCalculator } from './DebtToolsCalculator';
import { CashBackLowInterestCalculator, InterestCalculator, SimpleInterestCalculator, CompoundInterestCalculator, InterestRateCalculator } from './InterestToolsCalculator';
import { InvestmentCalculator, RetirementCalculator, FourOhOneKCalculator, RothIraCalculator, IraCalculator } from './RetirementToolsCalculator';
import { RmdCalculator, AnnuityCalculator, AnnuityPayoutCalculator, SavingsCalculator, CdCalculator } from './SavingsToolsCalculator';
import { IncomeTaxCalculator, SalaryCalculator, TakeHomePaycheckCalculator, SalesTaxCalculator, MarriageTaxCalculator } from './TaxToolsCalculator';
import { InflationCalculator, DepreciationCalculator, AverageReturnCalculator, MarginCalculator, DiscountCalculator } from './BusinessMathToolsCalculator';

interface Props {
  slug: string;
}

export function CalculatorRenderer({ slug }: Props) {
  switch (slug) {
    case 'age':                  return <AgeCalculator />;
    case 'bmi':                  return <BMICalculator />;
    case 'calorie':              return <CalorieCalculator />;
    case 'gpa':                  return <GPACalculator />;
    case 'loan':                 return <LoanCalculator />;
    case 'mortgage':             return <MortgageCalculator />;
    case 'mortgage-amortization': return <MortgageAmortizationCalculator />;
    case 'house-affordability':  return <HouseAffordabilityCalculator />;
    case 'rent':                 return <RentCalculator />;
    case 'rent-vs-buy':          return <RentVsBuyCalculator />;
    case 'percentage':           return <PercentageCalculator />;
    case 'tip':                  return <TipCalculator />;
    case 'rental-property':      return <RentalPropertyCalculator />;
    case 'real-estate':          return <RealEstateCalculator />;
    case 'fha-loan':             return <FHALoanCalculator />;
    case 'va-mortgage':          return <VAMortgageCalculator />;
    case 'home-equity-loan':     return <HomeEquityLoanCalculator />;
    case 'heloc':                return <HelocCalculator />;
    case 'down-payment':         return <DownPaymentCalculator />;
    case 'refinance':            return <RefinanceCalculator />;
    case 'mortgage-payoff':      return <MortgagePayoffCalculator />;
    case 'mortgage-uk':          return <MortgageUkCalculator />;
    case 'canadian-mortgage':    return <CanadianMortgageCalculator />;
    case 'personal-loan':        return <PersonalLoanCalculator />;
    case 'auto-loan':            return <AutoLoanCalculator />;
    case 'auto-lease':           return <AutoLeaseCalculator />;
    case 'boat-loan':            return <BoatLoanCalculator />;
    case 'payment':              return <PaymentCalculator />;
    case 'repayment':            return <RepaymentCalculator />;
    case 'student-loan':         return <StudentLoanCalculator />;
    case 'college-cost':         return <CollegeCostCalculator />;
    case 'credit-card':           return <CreditCardCalculator />;
    case 'credit-cards-payoff':   return <CreditCardsPayoffCalculator />;
    case 'debt-payoff':           return <DebtPayoffCalculator />;
    case 'debt-consolidation':    return <DebtConsolidationCalculator />;
    case 'debt-to-income':        return <DtiCalculator />;
    case 'cash-back-low-interest': return <CashBackLowInterestCalculator />;
    case 'interest':              return <InterestCalculator />;
    case 'simple-interest':       return <SimpleInterestCalculator />;
    case 'compound-interest':     return <CompoundInterestCalculator />;
    case 'interest-rate':         return <InterestRateCalculator />;
    case 'investment':            return <InvestmentCalculator />;
    case 'retirement':            return <RetirementCalculator />;
    case '401k':                  return <FourOhOneKCalculator />;
    case 'roth-ira':              return <RothIraCalculator />;
    case 'ira':                   return <IraCalculator />;
    case 'rmd':                   return <RmdCalculator />;
    case 'annuity':               return <AnnuityCalculator />;
    case 'annuity-payout':        return <AnnuityPayoutCalculator />;
    case 'savings':               return <SavingsCalculator />;
    case 'cd':                    return <CdCalculator />;
    case 'income-tax':             return <IncomeTaxCalculator />;
    case 'salary':                 return <SalaryCalculator />;
    case 'take-home-paycheck':    return <TakeHomePaycheckCalculator />;
    case 'sales-tax':              return <SalesTaxCalculator />;
    case 'marriage-tax':           return <MarriageTaxCalculator />;
    case 'inflation':              return <InflationCalculator />;
    case 'depreciation':           return <DepreciationCalculator />;
    case 'average-return':         return <AverageReturnCalculator />;
    case 'margin':                 return <MarginCalculator />;
    case 'discount':               return <DiscountCalculator />;
    default:                     return <div className="p-8 text-slate-500 text-center">Calculator not found.</div>;
  }
}
