'use client';

import { PaceAdvancedCalculator, GfrAdvancedCalculator, BacAdvancedCalculator } from './ClinicalAdvancedCalculator';
import { ScientificCoreCalculator, FractionCoreCalculator, StandardDeviationCalculator, RatioCoreCalculator, QuadraticFormulaCalculator } from './MathCoreCalculator';
import { ExponentCalculator, RootCalculator, LogCalculator, PercentErrorCalculator, RoundingCalculator } from './MathExtendedCalculator';
import { TriangleCalculator, VolumeCalculator, NumberSequenceCalculator, BinaryCalculator, HexCalculator, HalfLifeCalculator, SlopeCalculator } from './MathGeometryCalculator';
import { AreaCalculator, DistanceCalculator, SampleSizeCalculator, ProbabilityCalculator, StatisticsCalculator, PermutationCombinationCalculator } from './MathStatsCalculator';
import { CircleCalculator, SurfaceAreaCalculator, PythagoreanTheoremCalculator, RightTriangleCalculator, LeastCommonMultipleCalculator, GreatestCommonFactorCalculator, PrimeFactorizationCalculator } from './GeometryAdvancedCalculator';
import { ZScoreCalculator, ConfidenceIntervalCalculator, MeanMedianModeRangeCalculator } from './StatisticsAdvancedCalculator';
import { FactorCalculator, MatrixCalculator, BasicCalculator, LongDivisionCalculator, AverageCalculator, PValueCalculator } from './NumberToolsCalculator';
import { ScientificNotationCalculator, BigNumberCalculator, CommonFactorCalculator, DateCalculator, TimeCalculator, HoursCalculator, GradeCalculator, HeightCalculator, ConcreteCalculator } from './MiscToolsCalculator';
import { IpSubnetCalculator, ConversionCalculator } from './UtilityToolsCalculator';
import { AgeCalculator } from './AgeCalculator';
import { BMICalculator } from './BMICalculator';
import { CalorieCalculator } from './CalorieCalculator';
import { GPACalculator } from './GPACalculator';
import { LoanCalculator } from './LoanCalculator';
import { MortgageCalculator } from './MortgageCalculator';
import { MortgageAmortizationCalculator } from './MortgageAmortizationCalculator';
import { HouseAffordabilityCalculator } from './HouseAffordabilityCalculator';
import { RentCalculator } from './RentCalculator';
import { RentVsBuyCalculator } from './RentVsBuyCalculator';
import { PercentageCalculator } from './PercentageCalculator';
import { TipCalculator } from './TipCalculator';
import { RentalPropertyCalculator } from './RentalPropertyCalculator';
import { RealEstateCalculator } from './RealEstateCalculator';
import { FHALoanCalculator } from './FHALoanCalculator';
import { VAMortgageCalculator } from './VAMortgageCalculator';
import { HomeEquityLoanCalculator } from './HomeEquityLoanCalculator';
import { HelocCalculator } from './HelocCalculator';
import { DownPaymentCalculator } from './DownPaymentCalculator';
import { RefinanceCalculator } from './RefinanceCalculator';
import { MortgagePayoffCalculator } from './MortgagePayoffCalculator';
import { MortgageUkCalculator } from './MortgageUkCalculator';
import { CanadianMortgageCalculator } from './CanadianMortgageCalculator';
import { PersonalLoanCalculator } from './PersonalLoanCalculator';
import { AutoLoanCalculator } from './AutoLoanCalculator';
import { AutoLeaseCalculator } from './AutoLeaseCalculator';
import { BoatLoanCalculator } from './BoatLoanCalculator';
import { PaymentCalculator, RepaymentCalculator, StudentLoanCalculator } from './LoanProductCalculator';
import { CollegeCostCalculator } from './CollegeCostCalculator';
import { AmortizationCalculatorAdvanced, BondCalculator, MutualFundCalculator } from './FinancialAdvancedCalculator';
import { CreditUtilizationCalculator, DebtSnowballCalculator, DebtAvalancheCalculator } from './CreditAdvancedCalculator';
import { CreditCardCalculator, CreditCardsPayoffCalculator, DebtPayoffCalculator, DebtConsolidationCalculator, DtiCalculator } from './DebtToolsCalculator';
import { CashBackLowInterestCalculator, InterestCalculator, SimpleInterestCalculator, CompoundInterestCalculator, InterestRateCalculator } from './InterestToolsCalculator';
import { InvestmentCalculator, RetirementCalculator, FourOhOneKCalculator, RothIraCalculator, IraCalculator } from './RetirementToolsCalculator';
import { RmdCalculator, AnnuityCalculator, AnnuityPayoutCalculator, SavingsCalculator, CdCalculator } from './SavingsToolsCalculator';
import { IncomeTaxCalculator, SalaryCalculator, TakeHomePaycheckCalculator, SalesTaxCalculator, MarriageTaxCalculator } from './TaxToolsCalculator';
import { InflationCalculator, DepreciationCalculator, AverageReturnCalculator, MarginCalculator, DiscountCalculator } from './BusinessMathToolsCalculator';
import { PercentOffCalculator, BusinessLoanCalculator, LeaseCalculator, BudgetCalculator, IrrCalculator } from './CommercialToolsCalculator';
import { RoiCalculator, AprCalculator, PaybackPeriodCalculator, PresentValueCalculator, FutureValueCalculator } from './ValuationToolsCalculator';
import { EstateTaxCalculator, FinanceCalculator, PensionCalculator, SocialSecurityCalculator, CurrencyCalculator } from './MacroFinanceToolsCalculator';
import { CommissionCalculator, VatCalculator, AnorexicBmiCalculator } from './HealthSalesToolsCalculator';
import { BmrCalculator, TdeeCalculator, MacroCalculator, ProteinCalculator, CarbohydrateCalculator } from './MetabolicToolsCalculator';
import { FatIntakeCalculator, IdealWeightCalculator, HealthyWeightCalculator, LeanBodyMassCalculator, CaloriesBurnedCalculator } from './BodyCompositionToolsCalculator';
import { TargetHeartRateCalculator, OneRepMaxCalculator, WeightWatcherPointsCalculator, OverweightCalculator, BodyFatCalculator } from './HeartStrengthToolsCalculator';
import { ArmyBodyFatCalculator, BodySurfaceAreaCalculator, BodyTypeCalculator, PregnancyCalculator, PregnancyWeightGainCalculator } from './ClinicalMetricsToolsCalculator';
import { PregnancyConceptionCalculator, DueDateCalculator, OvulationCalculator, ConceptionCalculator, PeriodCalculator } from './CycleToolsCalculator';

interface Props {
  slug: string;
}

export function CalculatorRenderer({ slug }: Props) {
  switch (slug) {
    case 'exponent':             return <ExponentCalculator />;
    case 'root':                 return <RootCalculator />;
    case 'log':                  return <LogCalculator />;
    case 'percent-error':        return <PercentErrorCalculator />;
    case 'rounding':             return <RoundingCalculator />;
    case 'scientific-notation': return <ScientificNotationCalculator />;
    case 'big-number': return <BigNumberCalculator />;
    case 'common-factor': return <CommonFactorCalculator />;
    case 'date': return <DateCalculator />;
    case 'time': return <TimeCalculator />;
    case 'hours': return <HoursCalculator />;
    case 'grade': return <GradeCalculator />;
    case 'height': return <HeightCalculator />;
    case 'concrete': return <ConcreteCalculator />;
    case 'ip-subnet': return <IpSubnetCalculator />;
    case 'conversion': return <ConversionCalculator />;
    case 'factor': return <FactorCalculator />;
    case 'matrix': return <MatrixCalculator />;
    case 'basic': return <BasicCalculator />;
    case 'long-division': return <LongDivisionCalculator />;
    case 'average': return <AverageCalculator />;
    case 'p-value': return <PValueCalculator />;
    case 'circle': return <CircleCalculator />;
    case 'surface-area': return <SurfaceAreaCalculator />;
    case 'pythagorean-theorem': return <PythagoreanTheoremCalculator />;
    case 'right-triangle': return <RightTriangleCalculator />;
    case 'least-common-multiple': return <LeastCommonMultipleCalculator />;
    case 'greatest-common-factor': return <GreatestCommonFactorCalculator />;
    case 'prime-factorization': return <PrimeFactorizationCalculator />;
    case 'z-score':               return <ZScoreCalculator />;
    case 'confidence-interval':   return <ConfidenceIntervalCalculator />;
    case 'mean-median-mode-range': return <MeanMedianModeRangeCalculator />;
    case 'area':                        return <AreaCalculator />;
    case 'distance':                    return <DistanceCalculator />;
    case 'sample-size':                 return <SampleSizeCalculator />;
    case 'probability':                 return <ProbabilityCalculator />;
    case 'statistics':                  return <StatisticsCalculator />;
    case 'permutation-and-combination': return <PermutationCombinationCalculator />;
    case 'triangle':             return <TriangleCalculator />;
    case 'volume':               return <VolumeCalculator />;
    case 'number-sequence':      return <NumberSequenceCalculator />;
    case 'binary':               return <BinaryCalculator />;
    case 'hex':                  return <HexCalculator />;
    case 'half-life':            return <HalfLifeCalculator />;
    case 'slope':                return <SlopeCalculator />;
    case 'scientific':           return <ScientificCoreCalculator />;
    case 'fraction':             return <FractionCoreCalculator />;
    case 'standard-deviation':   return <StandardDeviationCalculator />;
    case 'ratio':                return <RatioCoreCalculator />;
    case 'quadratic-formula':    return <QuadraticFormulaCalculator />;
    case 'pace':                 return <PaceAdvancedCalculator />;
    case 'gfr':                  return <GfrAdvancedCalculator />;
    case 'bac':                  return <BacAdvancedCalculator />;
    case 'age':                  return <AgeCalculator />;
    case 'bmi':                  return <BMICalculator />;
    case 'calorie':              return <CalorieCalculator />;
    case 'gpa':                  return <GPACalculator />;
    case 'loan':                 return <LoanCalculator />;
    case 'mortgage':             return <MortgageCalculator />;
    case 'mortgage-amortization': return <MortgageAmortizationCalculator />;
    case 'house-affordability':  return <HouseAffordabilityCalculator />;
    case 'rent':                 return <RentCalculator />;
    case 'rent-vs-buy':          return <RentVsBuyCalculator />;
    case 'percentage':           return <PercentageCalculator />;
    case 'tip':                  return <TipCalculator />;
    case 'rental-property':      return <RentalPropertyCalculator />;
    case 'real-estate':          return <RealEstateCalculator />;
    case 'fha-loan':             return <FHALoanCalculator />;
    case 'va-mortgage':          return <VAMortgageCalculator />;
    case 'home-equity-loan':     return <HomeEquityLoanCalculator />;
    case 'heloc':                return <HelocCalculator />;
    case 'down-payment':         return <DownPaymentCalculator />;
    case 'refinance':            return <RefinanceCalculator />;
    case 'mortgage-payoff':      return <MortgagePayoffCalculator />;
    case 'mortgage-uk':          return <MortgageUkCalculator />;
    case 'canadian-mortgage':    return <CanadianMortgageCalculator />;
    case 'personal-loan':        return <PersonalLoanCalculator />;
    case 'auto-loan':            return <AutoLoanCalculator />;
    case 'auto-lease':           return <AutoLeaseCalculator />;
    case 'boat-loan':            return <BoatLoanCalculator />;
    case 'payment':              return <PaymentCalculator />;
    case 'repayment':            return <RepaymentCalculator />;
    case 'student-loan':         return <StudentLoanCalculator />;
    case 'college-cost':         return <CollegeCostCalculator />;
    case 'amortization':         return <AmortizationCalculatorAdvanced />;
    case 'bond':                 return <BondCalculator />;
    case 'mutual-fund':          return <MutualFundCalculator />;
    case 'credit-utilization':     return <CreditUtilizationCalculator />;
    case 'debt-snowball':         return <DebtSnowballCalculator />;
    case 'debt-avalanche':        return <DebtAvalancheCalculator />;
    case 'credit-card':           return <CreditCardCalculator />;
    case 'credit-cards-payoff':   return <CreditCardsPayoffCalculator />;
    case 'debt-payoff':           return <DebtPayoffCalculator />;
    case 'debt-consolidation':    return <DebtConsolidationCalculator />;
    case 'debt-to-income':        return <DtiCalculator />;
    case 'cash-back-low-interest': return <CashBackLowInterestCalculator />;
    case 'interest':              return <InterestCalculator />;
    case 'simple-interest':       return <SimpleInterestCalculator />;
    case 'compound-interest':     return <CompoundInterestCalculator />;
    case 'interest-rate':         return <InterestRateCalculator />;
    case 'investment':            return <InvestmentCalculator />;
    case 'retirement':            return <RetirementCalculator />;
    case '401k':                  return <FourOhOneKCalculator />;
    case 'roth-ira':              return <RothIraCalculator />;
    case 'ira':                   return <IraCalculator />;
    case 'rmd':                   return <RmdCalculator />;
    case 'annuity':               return <AnnuityCalculator />;
    case 'annuity-payout':        return <AnnuityPayoutCalculator />;
    case 'savings':               return <SavingsCalculator />;
    case 'cd':                    return <CdCalculator />;
    case 'income-tax':             return <IncomeTaxCalculator />;
    case 'salary':                 return <SalaryCalculator />;
    case 'take-home-paycheck':    return <TakeHomePaycheckCalculator />;
    case 'sales-tax':              return <SalesTaxCalculator />;
    case 'marriage-tax':           return <MarriageTaxCalculator />;
    case 'inflation':              return <InflationCalculator />;
    case 'depreciation':           return <DepreciationCalculator />;
    case 'average-return':         return <AverageReturnCalculator />;
    case 'margin':                 return <MarginCalculator />;
    case 'discount':               return <DiscountCalculator />;
    case 'percent-off':             return <PercentOffCalculator />;
    case 'business-loan':           return <BusinessLoanCalculator />;
    case 'lease':                   return <LeaseCalculator />;
    case 'budget':                  return <BudgetCalculator />;
    case 'irr':                     return <IrrCalculator />;
    case 'roi':                     return <RoiCalculator />;
    case 'apr':                     return <AprCalculator />;
    case 'payback-period':          return <PaybackPeriodCalculator />;
    case 'present-value':           return <PresentValueCalculator />;
    case 'future-value':            return <FutureValueCalculator />;
    case 'estate-tax':              return <EstateTaxCalculator />;
    case 'finance':                 return <FinanceCalculator />;
    case 'pension':                 return <PensionCalculator />;
    case 'social-security':         return <SocialSecurityCalculator />;
    case 'currency':                return <CurrencyCalculator />;
    case 'commission':              return <CommissionCalculator />;
    case 'vat':                     return <VatCalculator />;
    case 'anorexic-bmi':            return <AnorexicBmiCalculator />;
    case 'bmr':                     return <BmrCalculator />;
    case 'tdee':                    return <TdeeCalculator />;
    case 'macro':                   return <MacroCalculator />;
    case 'protein':                 return <ProteinCalculator />;
    case 'carbohydrate':            return <CarbohydrateCalculator />;
    case 'fat-intake':              return <FatIntakeCalculator />;
    case 'ideal-weight':            return <IdealWeightCalculator />;
    case 'healthy-weight':          return <HealthyWeightCalculator />;
    case 'lean-body-mass':          return <LeanBodyMassCalculator />;
    case 'calories-burned':         return <CaloriesBurnedCalculator />;
    case 'target-heart-rate':       return <TargetHeartRateCalculator />;
    case 'one-rep-max':             return <OneRepMaxCalculator />;
    case 'weight-watcher-points':   return <WeightWatcherPointsCalculator />;
    case 'overweight':              return <OverweightCalculator />;
    case 'body-fat':                return <BodyFatCalculator />;
    case 'army-body-fat':            return <ArmyBodyFatCalculator />;
    case 'body-surface-area':        return <BodySurfaceAreaCalculator />;
    case 'body-type':                return <BodyTypeCalculator />;
    case 'pregnancy':                return <PregnancyCalculator />;
    case 'pregnancy-weight-gain':    return <PregnancyWeightGainCalculator />;
    case 'pregnancy-conception':     return <PregnancyConceptionCalculator />;
    case 'due-date':                 return <DueDateCalculator />;
    case 'ovulation':                return <OvulationCalculator />;
    case 'conception':               return <ConceptionCalculator />;
    case 'period':                   return <PeriodCalculator />;
    default:                     return <div className="p-8 text-slate-500 text-center">Calculator not found.</div>;
  }
}
