'use client';

import { useMemo, useState } from 'react';
import { calculateCreditCard, calculateCreditCardsPayoff, calculateDebtConsolidation, calculateDti, simulatePayoff } from '@/lib/calculators/debtProducts';
import { formatCurrency } from '@/lib/utils';
import { Field, inputClass, InputsPanel, ResultCard, ResultsPanel } from './ResultCard';

export type DebtToolMode = 'credit-card' | 'credit-cards-payoff' | 'debt-payoff' | 'debt-consolidation' | 'dti';
interface Props { mode: DebtToolMode }
function Num({ id, label, value, onChange, min = 0, step = 100, max = 10000000, hint }: { id: string; label: string; value: number; onChange: (v: number) => void; min?: number; step?: number; max?: number; hint?: string }) { return <Field label={label} htmlFor={id} hint={hint}><input id={id} type="number" value={value} min={min} max={max} step={step} aria-label={label} onChange={(e) => onChange(+e.target.value || 0)} className={inputClass} /></Field>; }
export function DebtToolsCalculator({ mode }: Props) {
  const [balance, setBalance] = useState(12000); const [apr, setApr] = useState(22.99); const [payment, setPayment] = useState(350); const [minimumPercent, setMinimumPercent] = useState(2); const [minimumFloor, setMinimumFloor] = useState(25); const [card2, setCard2] = useState(5000); const [card3, setCard3] = useState(2500); const [income, setIncome] = useState(6000); const [housing, setHousing] = useState(1500); const [proposed, setProposed] = useState(500); const [newApr, setNewApr] = useState(10); const [termYears, setTermYears] = useState(5); const [fees, setFees] = useState(500);
  const title = mode === 'credit-card' ? 'Credit Card Calculator' : mode === 'credit-cards-payoff' ? 'Credit Cards Payoff Calculator' : mode === 'debt-payoff' ? 'Debt Payoff Calculator' : mode === 'debt-consolidation' ? 'Debt Consolidation Calculator' : 'Debt-to-Income Ratio Calculator';
  const view = useMemo(() => {
    if (mode === 'credit-card') { const r = calculateCreditCard(balance, apr, minimumPercent, minimumFloor); return { primary: r.minimumPayment, primaryLabel: 'First Minimum Payment', a: r.totalInterest, aLabel: 'Total Interest', b: r.totalPayments, bLabel: 'Total Payments', c: r.payments, cLabel: 'Payments', note: r.status === 'payment-too-low' ? 'Minimum payment does not cover monthly interest.' : `${r.payments} payments under a fixed minimum model`, warning: r.status !== 'payable' }; }
    if (mode === 'credit-cards-payoff') { const r = calculateCreditCardsPayoff({ card1: { balance, apr, payment }, card2: { balance: card2, apr: 18.99, payment: Math.max(25, card2 * 0.03) }, card3: { balance: card3, apr: 24.99, payment: Math.max(25, card3 * 0.03) } }); return { primary: r.totalPayment, primaryLabel: 'Combined Monthly Payment', a: r.totalInterest, aLabel: 'Combined Interest', b: r.totalBalance, bLabel: 'Total Balance', c: r.payoffMonths, cLabel: 'Longest Payoff (months)', note: `${r.cards.filter((c) => c.status === 'payable').length} cards simulated`, warning: r.cards.some((c) => c.status === 'payment-too-low') }; }
    if (mode === 'debt-payoff') { const r = simulatePayoff(balance, apr, payment); return { primary: r.monthlyPayment, primaryLabel: 'Monthly Payment', a: r.totalInterest, aLabel: 'Total Interest', b: r.totalPayments, bLabel: 'Total Payments', c: r.payments, cLabel: 'Payoff (months)', note: r.status === 'payment-too-low' ? 'Payment does not cover monthly interest.' : `${r.payments} payments to clear the balance`, warning: r.status !== 'payable' }; }
    if (mode === 'debt-consolidation') { const r = calculateDebtConsolidation(balance, apr, payment, newApr, termYears, fees); return { primary: r.newPayment, primaryLabel: 'New Monthly Payment', a: r.monthlySavings, aLabel: 'Monthly Savings', b: r.currentInterest, bLabel: 'Current Interest', c: r.newInterest, cLabel: 'New Interest', note: `New term ${termYears} years; fees ${formatCurrency(fees)}`, warning: r.status === 'payment-too-low' }; }
    const r = calculateDti(income, balance, housing, proposed); return { primary: r.proposedDti, primaryLabel: 'Proposed DTI (%)', a: r.dti, aLabel: 'Current DTI (%)', b: r.monthlyDebt, bLabel: 'Monthly Debt', c: r.headroom, cLabel: 'Headroom to 36%', note: r.status === 'within-range' ? 'Proposed DTI is within the 36% reference line.' : 'Proposed DTI is above the 36% reference line.', warning: r.status === 'high' };
  }, [mode, balance, apr, payment, minimumPercent, minimumFloor, card2, card3, income, housing, proposed, newApr, termYears, fees]);
  const split = typeof view.primary === 'number' && view.primary > 0 ? Math.min(100, Math.max(0, (view.primary / Math.max(view.primary + view.a, 1)) * 100)) : 0;
  return <div className="space-y-6"><div className="grid grid-cols-1 lg:grid-cols-2 gap-6"><InputsPanel title={`${title} Inputs`}>
    {mode === 'dti' ? <><Num id="dti-income" label="Gross Monthly Income ($)" value={income} onChange={setIncome} /><Num id="dti-debt" label="Monthly Debt Payments ($)" value={balance} onChange={setBalance} /><Num id="dti-housing" label="Housing Payment ($)" value={housing} onChange={setHousing} /><Num id="dti-proposed" label="Proposed New Debt ($)" value={proposed} onChange={setProposed} /></> : <><Num id={`${mode}-balance`} label={mode === 'credit-cards-payoff' ? 'Card 1 Balance ($)' : 'Balance ($)'} value={balance} onChange={setBalance} hint="Enter a non-negative balance." /><Num id={`${mode}-apr`} label="APR (%)" value={apr} step={0.01} max={100} onChange={setApr} />{mode === 'credit-card' && <><Num id="card-min-percent" label="Minimum Payment (%)" value={minimumPercent} step={0.1} max={100} onChange={setMinimumPercent} /><Num id="card-min-floor" label="Minimum Floor ($)" value={minimumFloor} onChange={setMinimumFloor} /></>}{mode === 'credit-cards-payoff' && <><Num id="card-two" label="Card 2 Balance ($)" value={card2} onChange={setCard2} /><Num id="card-three" label="Card 3 Balance ($)" value={card3} onChange={setCard3} /></>}{mode === 'debt-payoff' && <Num id="debt-payment" label="Monthly Payment ($)" value={payment} onChange={setPayment} />}{mode === 'debt-consolidation' && <><Num id="consolidation-payment" label="Current Monthly Payment ($)" value={payment} onChange={setPayment} /><Num id="consolidation-apr" label="New APR (%)" value={newApr} step={0.01} max={100} onChange={setNewApr} /><Num id="consolidation-term" label="New Term (years)" value={termYears} min={1} max={50} step={1} onChange={setTermYears} /><Num id="consolidation-fees" label="Consolidation Fees ($)" value={fees} onChange={setFees} /></>}</>}
  </InputsPanel><ResultsPanel title={`Live ${title} Results`}><ResultCard highlight label={view.primaryLabel} value={mode === 'dti' ? `${view.primary.toFixed(1)}%` : formatCurrency(view.primary)} sub={view.note} /><ResultCard label={view.aLabel} value={mode === 'dti' ? `${view.a.toFixed(1)}%` : formatCurrency(view.a)} /><ResultCard label={view.bLabel} value={mode === 'dti' ? formatCurrency(view.b) : mode === 'credit-card' || mode === 'debt-payoff' ? formatCurrency(view.b) : formatCurrency(view.b)} /><ResultCard label={view.cLabel} value={mode === 'dti' ? `${view.c.toFixed(1)}%` : mode === 'credit-card' || mode === 'credit-cards-payoff' || mode === 'debt-payoff' ? `${view.c}` : formatCurrency(view.c)} /><div className="sm:col-span-2 space-y-2" aria-label="Debt and interest split"><div className="flex justify-between text-[11px] text-slate-400"><span>Primary {split.toFixed(1)}%</span><span>Other {(100 - split).toFixed(1)}%</span></div><div className="h-3 rounded-full overflow-hidden bg-red-500/30 flex"><div className="bg-blue-500" style={{ width: `${split}%` }} /><div className="bg-red-400 flex-1" /></div></div>{view.warning && <p role="alert" className="sm:col-span-2 rounded-lg bg-amber-500/10 px-3 py-2 text-xs text-amber-200">{view.note}</p>}</ResultsPanel></div></div>;
}
export function CreditCardCalculator() { return <DebtToolsCalculator mode="credit-card" />; }
export function CreditCardsPayoffCalculator() { return <DebtToolsCalculator mode="credit-cards-payoff" />; }
export function DebtPayoffCalculator() { return <DebtToolsCalculator mode="debt-payoff" />; }
export function DebtConsolidationCalculator() { return <DebtToolsCalculator mode="debt-consolidation" />; }
export function DtiCalculator() { return <DebtToolsCalculator mode="dti" />; }
