'use client';
import { useMemo, useState } from 'react';
import { Field, inputClass, InputsPanel, ResultCard, ResultsPanel } from './ResultCard';

type Mode = 'bmr' | 'tdee' | 'macro' | 'protein' | 'carbohydrate';
export function MetabolicToolsCalculator({ mode }: { mode: Mode }) {
  const [weight, setWeight] = useState(70); const [height, setHeight] = useState(175); const [age, setAge] = useState(30); const [rate, setRate] = useState(1.55); const [calories, setCalories] = useState(2200);
  const title = mode === 'bmr' ? 'BMR Calculator' : mode === 'tdee' ? 'TDEE Calculator' : mode === 'macro' ? 'Macro Calculator' : mode === 'protein' ? 'Protein Calculator' : 'Carbohydrate Calculator';
  const x = useMemo(() => { const bmr = 10 * weight + 6.25 * height - 5 * age + 5; if (mode === 'bmr') return { primary: bmr, secondary: bmr * .9, label: 'Estimated BMR (kcal/day)' }; if (mode === 'tdee') return { primary: bmr * rate, secondary: bmr, label: 'Estimated TDEE (kcal/day)' }; if (mode === 'protein') return { primary: weight * rate, secondary: weight * 0.8, label: 'Protein (g/day)' }; if (mode === 'carbohydrate') return { primary: calories * rate / 4, secondary: calories, label: 'Carbohydrates (g/day)' }; return { primary: calories * .5 / 4, secondary: calories * .25 / 9, label: 'Carbs (g/day)' }; }, [mode, weight, height, age, rate, calories]);
  return <div className="grid grid-cols-1 lg:grid-cols-2 gap-6"><InputsPanel title={`${title} Inputs`}><Field label="Weight (kg)" htmlFor={`${mode}-weight`}><input id={`${mode}-weight`} type="number" min={0} step={0.1} value={weight} onChange={e => setWeight(+e.target.value || 0)} className={inputClass}/></Field><Field label="Height (cm)" htmlFor={`${mode}-height`}><input id={`${mode}-height`} type="number" min={0} step={0.1} value={height} onChange={e => setHeight(+e.target.value || 0)} className={inputClass}/></Field><Field label="Age (years)" htmlFor={`${mode}-age`}><input id={`${mode}-age`} type="number" min={0} value={age} onChange={e => setAge(+e.target.value || 0)} className={inputClass}/></Field><Field label={mode === 'tdee' ? 'Activity multiplier' : mode === 'protein' ? 'Protein g/kg' : mode === 'carbohydrate' ? 'Carb share (%)' : 'Daily calories'} htmlFor={`${mode}-rate`}><input id={`${mode}-rate`} type="number" min={0} step={0.01} value={mode === 'protein' ? rate : mode === 'carbohydrate' ? rate * 100 : mode === 'tdee' ? rate : calories} onChange={e => mode === 'protein' || mode === 'tdee' ? setRate(+e.target.value || 0) : mode === 'carbohydrate' ? setRate((+e.target.value || 0) / 100) : setCalories(+e.target.value || 0)} className={inputClass}/></Field></InputsPanel><ResultsPanel title={`Live ${title} Results`}><ResultCard highlight label={x.label} value={x.primary.toFixed(2)} sub="Results computed instantly — your data never leaves your device."/><ResultCard label="Reference / Secondary" value={x.secondary.toFixed(2)}/><ResultCard label="Weight" value={`${weight} kg`}/></ResultsPanel></div>;
}
export const BmrCalculator = () => <MetabolicToolsCalculator mode="bmr"/>; export const TdeeCalculator = () => <MetabolicToolsCalculator mode="tdee"/>; export const MacroCalculator = () => <MetabolicToolsCalculator mode="macro"/>; export const ProteinCalculator = () => <MetabolicToolsCalculator mode="protein"/>; export const CarbohydrateCalculator = () => <MetabolicToolsCalculator mode="carbohydrate"/>;
