'use client';
import {useMemo,useState} from 'react';
import {project401k,projectInvestment,projectIra,projectRetirement,projectRothIra} from '@/lib/calculators/retirementProducts';
import {formatCurrency} from '@/lib/utils';
import {Field,inputClass,InputsPanel,ResultCard,ResultsPanel} from './ResultCard';
type Mode='investment'|'retirement'|'401k'|'roth-ira'|'ira';
function Num({id,label,value,onChange,step=100,max=10000000}:{id:string;label:string;value:number;onChange:(v:number)=>void;step?:number;max?:number}){return <Field label={label} htmlFor={id}><input id={id} type="number" value={value} min={0} max={max} step={step} aria-label={label} onChange={e=>onChange(+e.target.value||0)} className={inputClass}/></Field>}
export function RetirementToolsCalculator({mode}:{mode:Mode}){const[current,setCurrent]=useState(10000),[monthly,setMonthly]=useState(500),[rate,setRate]=useState(7),[years,setYears]=useState(20),[match,setMatch]=useState(3),[employer,setEmployer]=useState(100);const title=mode==='investment'?'Investment Calculator':mode==='retirement'?'Retirement Calculator':mode==='401k'?'401K Calculator':mode==='roth-ira'?'Roth IRA Calculator':'IRA Calculator';const r=useMemo(()=>mode==='investment'?projectInvestment(current,monthly,rate,years,12):mode==='retirement'?projectRetirement(current,monthly,employer,rate,years):mode==='401k'?project401k(current,monthly,match,rate,years):mode==='roth-ira'?projectRothIra(current,monthly,rate,years):projectIra(current,monthly,rate,years),[mode,current,monthly,rate,years,match,employer]);const split=Math.min(100,Math.max(0,r.total? r.growth/r.total*100:0));return <div className="space-y-6"><div className="grid grid-cols-1 lg:grid-cols-2 gap-6"><InputsPanel title={`${title} Inputs`}><Num id={`${mode}-current`} label="Current Balance ($)" value={current} onChange={setCurrent}/><Num id={`${mode}-monthly`} label="Monthly Contribution ($)" value={monthly} onChange={setMonthly}/><Num id={`${mode}-rate`} label="Annual Return (%)" value={rate} step={0.01} max={100} onChange={setRate}/><Num id={`${mode}-years`} label="Years" value={years} step={1} max={100} onChange={setYears}/>{mode==='retirement'&&<Num id="retirement-employer" label="Employer Monthly Contribution ($)" value={employer} onChange={setEmployer}/>} {mode==='401k'&&<Num id="401k-match" label="Employer Match (%)" value={match} step={0.1} max={100} onChange={setMatch}/>}</InputsPanel><ResultsPanel title={`Live ${title} Results`}><ResultCard highlight label="Projected Future Value" value={formatCurrency(r.total)} sub={`${r.periods} compounding periods`}/><ResultCard label="Growth" value={formatCurrency(r.growth)}/><ResultCard label="Contributions" value={formatCurrency(r.contributions)}/><ResultCard label="Starting Principal" value={formatCurrency(r.principal)}/><div className="sm:col-span-2"><div className="flex justify-between text-[11px] text-slate-400"><span>Growth {split.toFixed(1)}%</span><span>Principal/contributions {(100-split).toFixed(1)}%</span></div><div className="h-3 rounded-full overflow-hidden bg-red-500/30 flex"><div className="bg-blue-500" style={{width:`${split}%`}}/><div className="bg-red-400 flex-1"/></div></div></ResultsPanel></div></div>}
export const InvestmentCalculator=()=> <RetirementToolsCalculator mode="investment"/>;export const RetirementCalculator=()=> <RetirementToolsCalculator mode="retirement"/>;export const FourOhOneKCalculator=()=> <RetirementToolsCalculator mode="401k"/>;export const RothIraCalculator=()=> <RetirementToolsCalculator mode="roth-ira"/>;export const IraCalculator=()=> <RetirementToolsCalculator mode="ira"/>;
