import { Plus } from 'lucide-react';
import { ContentCard } from '@/components/admin/Card';
import { DataTable, Column } from '@/components/admin/DataTable';

export const metadata = { title: 'AI Articles — Admin' };

// Columns definition — no fake rows
type Article = { id: string; title: string; status: string; updatedAt: string };

const columns: Column<Article>[] = [
  { key: 'title',     header: 'Title' },
  { key: 'status',    header: 'Status',   className: 'w-28' },
  { key: 'updatedAt', header: 'Updated',  className: 'w-36' },
];

export default function ArticlesPage() {
  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-bold text-[var(--text-primary)]">AI Articles</h1>
          <p className="text-sm text-[var(--text-muted)] mt-0.5">
            Manage AI-generated article content.
          </p>
        </div>
        <button
          disabled
          className="inline-flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-semibold bg-blue-600 text-white opacity-50 cursor-not-allowed"
        >
          <Plus className="w-3.5 h-3.5" />
          New Article
        </button>
      </div>

      <ContentCard noPadding>
        <DataTable<Article>
          columns={columns}
          data={[]}
          keyField="id"
          emptyTitle="No articles yet"
          emptyDescription="Articles generated by AI will appear here."
        />
      </ContentCard>
    </div>
  );
}
