import type { CalculatorMeta } from '@/config/calculators';
import { CALCULATORS } from '@/config/calculators';
import type { CalcContent } from '@/config/calculator-content';
import { getCalculatorSpec, listFunctionalCalculators } from '@/config/calculator-engine';
import omniData from '@/config/omni-full-database.json';

export interface OmniCalculatorEntry {
  slug: string;
  name: string;
  shortName: string;
  category: string;
  icon: string;
  description: string;
  keywords: string[];
  inputs: Array<{
    name: string;
    label: string;
    type: 'number' | 'text' | 'select';
    defaultValue?: number | string;
    min?: number;
    max?: number;
    step?: number;
    suffix?: string;
    helpText?: string;
  }>;
  outputs: Array<{ name: string; label: string; suffix?: string; highlight?: boolean }>;
  formula: { expression: string; variables: Array<{ symbol: string; definition: string }>; notes?: string };
  howToSteps: string[];
  faqs: Array<{ question: string; answer: string }>;
  examples: Array<{ title: string; scenario: string; steps: string[]; result: string }>;
}

const rawOmniList = (omniData && Array.isArray((omniData as { calculators?: unknown[] }).calculators)
  ? (omniData as { calculators: OmniCalculatorEntry[] }).calculators
  : []) as OmniCalculatorEntry[];

const validOmniList = rawOmniList.filter(
  (item): item is OmniCalculatorEntry =>
    Boolean(item) &&
    typeof item.slug === 'string' &&
    item.slug.trim().length > 0 &&
    typeof item.name === 'string' &&
    item.name.trim().length > 0
);

const functionalSlugs = new Set(listFunctionalCalculators());
const staticBySlug = new Map(CALCULATORS.map((calculator) => [calculator.slug, calculator]));

// The imported Omni JSON is metadata-only and its schema is not executable by this app.
// When it is not compatible, publish the verified engine inventory instead. This prevents
// empty calculators and placeholder math from appearing in the public catalog.
const functionalCatalog: OmniCalculatorEntry[] = listFunctionalCalculators()
  .map((slug) => {
    const spec = getCalculatorSpec(slug);
    const staticCalc = staticBySlug.get(slug);
    return {
      slug,
      name: staticCalc?.name ?? spec.name,
      shortName: staticCalc?.shortName ?? spec.name.replace(/\s*Calculator\s*/i, ''),
      category: staticCalc?.category ?? spec.category,
      icon: staticCalc?.icon ?? '🧮',
      description: staticCalc?.description ?? `${spec.name} with verified inputs, formula, and calculation logic.`,
      keywords: staticCalc?.keywords ?? [slug, spec.name.toLowerCase()],
      inputs: spec.inputs.map((name) => ({
        name,
        label: name.replace(/[-_]/g, ' ').replace(/\b\w/g, (letter) => letter.toUpperCase()),
        type: name === 'values' || name === 'weights' ? 'text' : 'number',
        defaultValue: name === 'values' || name === 'weights' ? '10, 20, 30' : 1,
        helpText: name === 'values' || name === 'weights' ? 'Enter numbers separated by commas or spaces.' : undefined,
      })),
      outputs: spec.outputs.map((name, index) => ({
        name,
        label: name.replace(/[-_]/g, ' ').replace(/\b\w/g, (letter) => letter.toUpperCase()),
        highlight: index === 0,
      })),
      formula: {
        expression: spec.formula,
        variables: spec.inputs.map((name) => ({ symbol: name, definition: `${name.replace(/[-_]/g, ' ')} input.` })),
        notes: 'Formula and handler are registered in the verified calculator engine.',
      },
      howToSteps: [
        `Enter the required values for ${spec.name}.`,
        'Check units and constraints shown beside each input.',
        `Review the calculated ${spec.outputs.join(', ')} result.`,
      ],
      faqs: [
        { question: `What does the ${spec.name} calculate?`, answer: `${spec.name} applies the verified formula shown on the page to the supplied inputs.` },
        { question: 'Are placeholder formulas used?', answer: 'No. Public calculators are limited to registered handlers in the verified calculation engine.' },
      ],
      examples: [{
        title: 'Worked example',
        scenario: `Use the default values as a quick sanity check, then replace them with your own inputs.`,
        steps: spec.inputs.map((name, index) => `${index + 1}. Enter a valid ${name.replace(/[-_]/g, ' ')} value.`),
        result: 'The result is generated by the registered calculator handler.',
      }],
    };
  })
  .filter((item) => functionalSlugs.has(item.slug));

const omniCalculators: OmniCalculatorEntry[] = validOmniList.length > 0
  ? validOmniList.filter((item) => functionalSlugs.has(item.slug))
  : functionalCatalog;

const publishedCalculators = omniCalculators.length > 0 ? omniCalculators : functionalCatalog;

const omniBySlugMap = new Map<string, OmniCalculatorEntry>();
for (const item of publishedCalculators) {
  omniBySlugMap.set(item.slug, item);
  if (item.slug.endsWith('-calculator')) omniBySlugMap.set(item.slug.slice(0, -'-calculator'.length), item);
}

export function getOmniCalculator(slug: string): OmniCalculatorEntry | undefined {
  const clean = slug.toLowerCase().trim();
  const base = clean.endsWith('-calculator') ? clean.slice(0, -'-calculator'.length) : clean;
  return omniBySlugMap.get(base) || omniBySlugMap.get(clean);
}

export function getAllOmniCalculators(): OmniCalculatorEntry[] {
  return publishedCalculators;
}

export function getOmniCalculatorsByCategory(category: string): OmniCalculatorEntry[] {
  return publishedCalculators.filter((c) => c.category === category);
}

export function getOmniCategoryCount(): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const c of publishedCalculators) counts[c.category] = (counts[c.category] || 0) + 1;
  return counts;
}

export function toCalculatorMeta(omni: OmniCalculatorEntry): CalculatorMeta {
  return {
    slug: omni.slug,
    name: omni.name,
    shortName: omni.shortName,
    category: (omni.category as CalculatorMeta['category']) || 'math',
    description: omni.description,
    keywords: omni.keywords,
    icon: omni.icon,
  };
}

export function toCalcContent(omni: OmniCalculatorEntry): CalcContent {
  return { howToSteps: omni.howToSteps, formula: omni.formula, examples: omni.examples, faqs: omni.faqs };
}
